const _VendorFuels = [
  { vendor_id: 1001, fuel_type: 'Propane / LP' },
  { vendor_id: 1008, fuel_type: 'Oil' },
  { vendor_id: 1009, fuel_type: 'Oil' },
  { vendor_id: 1010, fuel_type: 'Oil' },
  { vendor_id: 1011, fuel_type: 'Electricity' },
  { vendor_id: 1015, fuel_type: 'Wood' },
  { vendor_id: 1016, fuel_type: 'Propane / LP' },
  { vendor_id: 1017, fuel_type: 'Oil' },
  { vendor_id: 1017, fuel_type: 'Propane / LP' },
  { vendor_id: 1019, fuel_type: 'Propane / LP' },
  { vendor_id: 1020, fuel_type: 'Electricity' },
  { vendor_id: 1021, fuel_type: 'Propane / LP' },
  { vendor_id: 1021, fuel_type: 'Oil' },
  { vendor_id: 1024, fuel_type: 'Oil' },
  { vendor_id: 1025, fuel_type: 'Electricity' },
  { vendor_id: 1030, fuel_type: 'Electricity' },
  { vendor_id: 1031, fuel_type: 'Electricity' },
  { vendor_id: 1032, fuel_type: 'Oil' },
  { vendor_id: 1044, fuel_type: 'Propane / LP' },
  { vendor_id: 1044, fuel_type: 'Oil' },
  { vendor_id: 1045, fuel_type: 'Propane / LP' },
  { vendor_id: 1045, fuel_type: 'Oil' },
  { vendor_id: 1046, fuel_type: 'Oil' },
  { vendor_id: 1047, fuel_type: 'Propane / LP' },
  { vendor_id: 1047, fuel_type: 'Oil' },
  { vendor_id: 1048, fuel_type: 'Oil' },
  { vendor_id: 1048, fuel_type: 'Propane / LP' },
  { vendor_id: 1050, fuel_type: 'Oil' },
  { vendor_id: 1050, fuel_type: 'Propane / LP' },
  { vendor_id: 1051, fuel_type: 'Propane / LP' },
  { vendor_id: 1053, fuel_type: 'Oil' },
  { vendor_id: 1054, fuel_type: 'Oil' },
  { vendor_id: 1056, fuel_type: 'Oil' },
  { vendor_id: 1058, fuel_type: 'Natural Gas' },
  { vendor_id: 1058, fuel_type: 'Electricity' },
  { vendor_id: 1059, fuel_type: 'Oil' },
  { vendor_id: 1060, fuel_type: 'Propane / LP' },
  { vendor_id: 1063, fuel_type: 'Oil' },
  { vendor_id: 1064, fuel_type: 'Natural Gas' },
  { vendor_id: 1064, fuel_type: 'Electricity' },
  { vendor_id: 1067, fuel_type: 'Electricity' },
  { vendor_id: 1069, fuel_type: 'Oil' },
  { vendor_id: 1070, fuel_type: 'Propane / LP' },
  { vendor_id: 1070, fuel_type: 'Oil' },
  { vendor_id: 1071, fuel_type: 'Oil' },
  { vendor_id: 1072, fuel_type: 'Oil' },
  { vendor_id: 1073, fuel_type: 'Propane / LP' },
  { vendor_id: 1073, fuel_type: 'Oil' },
  { vendor_id: 1074, fuel_type: 'Oil' },
  { vendor_id: 1075, fuel_type: 'Oil' },
  { vendor_id: 1078, fuel_type: 'Oil' },
  { vendor_id: 1078, fuel_type: 'Propane / LP' },
  { vendor_id: 1079, fuel_type: 'Propane / LP' },
  { vendor_id: 1080, fuel_type: 'Propane / LP' },
  { vendor_id: 1080, fuel_type: 'Oil' },
  { vendor_id: 1081, fuel_type: 'Electricity' },
  { vendor_id: 1082, fuel_type: 'Oil' },
  { vendor_id: 1083, fuel_type: 'Propane / LP' },
  { vendor_id: 1083, fuel_type: 'Oil' },
  { vendor_id: 1084, fuel_type: 'Electricity' },
  { vendor_id: 1085, fuel_type: 'Oil' },
  { vendor_id: 1086, fuel_type: 'Electricity' },
  { vendor_id: 1087, fuel_type: 'Oil' },
  { vendor_id: 1090, fuel_type: 'Oil' },
  { vendor_id: 1092, fuel_type: 'Propane / LP' },
  { vendor_id: 1092, fuel_type: 'Oil' },
  { vendor_id: 1098, fuel_type: 'Oil' },
  { vendor_id: 1098, fuel_type: 'Propane / LP' },
  { vendor_id: 1101, fuel_type: 'Propane / LP' },
  { vendor_id: 1102, fuel_type: 'Oil' },
  { vendor_id: 1103, fuel_type: 'Electricity' },
  { vendor_id: 1104, fuel_type: 'Electricity' },
  { vendor_id: 1105, fuel_type: 'Oil' },
  { vendor_id: 1106, fuel_type: 'Propane / LP' },
  { vendor_id: 1107, fuel_type: 'Propane / LP' },
  { vendor_id: 1108, fuel_type: 'Oil' },
  { vendor_id: 1109, fuel_type: 'Oil' },
  { vendor_id: 1111, fuel_type: 'Oil' },
  { vendor_id: 1112, fuel_type: 'Electricity' },
  { vendor_id: 1113, fuel_type: 'Oil' },
  { vendor_id: 1114, fuel_type: 'Electricity' },
  { vendor_id: 1116, fuel_type: 'Oil' },
  { vendor_id: 1117, fuel_type: 'Propane / LP' },
  { vendor_id: 1118, fuel_type: 'Electricity' },
  { vendor_id: 1119, fuel_type: 'Propane / LP' },
  { vendor_id: 1121, fuel_type: 'Oil' },
  { vendor_id: 1122, fuel_type: 'Oil' },
  { vendor_id: 1123, fuel_type: 'Propane / LP' },
  { vendor_id: 1124, fuel_type: 'Propane / LP' },
  { vendor_id: 1129, fuel_type: 'Oil' },
  { vendor_id: 1130, fuel_type: 'Oil' },
  { vendor_id: 1131, fuel_type: 'Propane / LP' },
  { vendor_id: 1132, fuel_type: 'Oil' },
  { vendor_id: 1133, fuel_type: 'Oil' },
  { vendor_id: 1134, fuel_type: 'Propane / LP' },
  { vendor_id: 1134, fuel_type: 'Oil' },
  { vendor_id: 1136, fuel_type: 'Propane / LP' },
  { vendor_id: 1137, fuel_type: 'Electricity' },
  { vendor_id: 1138, fuel_type: 'Oil' },
  { vendor_id: 1141, fuel_type: 'Propane / LP' },
  { vendor_id: 1141, fuel_type: 'Oil' },
  { vendor_id: 1142, fuel_type: 'Oil' },
  { vendor_id: 1142, fuel_type: 'Propane / LP' },
  { vendor_id: 1143, fuel_type: 'Propane / LP' },
  { vendor_id: 1143, fuel_type: 'Oil' },
  { vendor_id: 1144, fuel_type: 'Propane / LP' },
  { vendor_id: 1144, fuel_type: 'Oil' },
  { vendor_id: 1148, fuel_type: 'Natural Gas' },
  { vendor_id: 1149, fuel_type: 'Propane / LP' },
  { vendor_id: 1149, fuel_type: 'Oil' },
  { vendor_id: 1151, fuel_type: 'Propane / LP' },
  { vendor_id: 1154, fuel_type: 'Propane / LP' },
  { vendor_id: 1154, fuel_type: 'Oil' },
  { vendor_id: 1159, fuel_type: 'Oil' },
  { vendor_id: 1161, fuel_type: 'Propane / LP' },
  { vendor_id: 1161, fuel_type: 'Oil' },
  { vendor_id: 1162, fuel_type: 'Electricity' },
  { vendor_id: 1165, fuel_type: 'Oil' },
  { vendor_id: 1166, fuel_type: 'Electricity' },
  { vendor_id: 1167, fuel_type: 'Electricity' },
  { vendor_id: 1168, fuel_type: 'Electricity' },
  { vendor_id: 1169, fuel_type: 'Natural Gas' },
  { vendor_id: 1170, fuel_type: 'Electricity' },
  { vendor_id: 1171, fuel_type: 'Electricity' },
  { vendor_id: 1172, fuel_type: 'Electricity' },
  { vendor_id: 1173, fuel_type: 'Electricity' },
  { vendor_id: 1174, fuel_type: 'Natural Gas' },
  { vendor_id: 1174, fuel_type: 'Electricity' },
  { vendor_id: 1175, fuel_type: 'Electricity' },
  { vendor_id: 1176, fuel_type: 'Electricity' },
  { vendor_id: 1177, fuel_type: 'Natural Gas' },
  { vendor_id: 1178, fuel_type: 'Electricity' },
  { vendor_id: 1179, fuel_type: 'Electricity' },
  { vendor_id: 1180, fuel_type: 'Electricity' },
  { vendor_id: 1181, fuel_type: 'Electricity' },
  { vendor_id: 1182, fuel_type: 'Natural Gas' },
  { vendor_id: 1182, fuel_type: 'Electricity' },
  { vendor_id: 1183, fuel_type: 'Oil' },
  { vendor_id: 1184, fuel_type: 'Electricity' },
  { vendor_id: 1185, fuel_type: 'Electricity' },
  { vendor_id: 1186, fuel_type: 'Electricity' },
  { vendor_id: 1188, fuel_type: 'Natural Gas' },
  { vendor_id: 1188, fuel_type: 'Electricity' },
  { vendor_id: 1189, fuel_type: 'Natural Gas' },
  { vendor_id: 1189, fuel_type: 'Electricity' },
  { vendor_id: 1190, fuel_type: 'Electricity' },
  { vendor_id: 1191, fuel_type: 'Electricity' },
  { vendor_id: 1192, fuel_type: 'Electricity' },
  { vendor_id: 1193, fuel_type: 'Electricity' },
  { vendor_id: 1194, fuel_type: 'Electricity' },
  { vendor_id: 1195, fuel_type: 'Electricity' },
  { vendor_id: 1196, fuel_type: 'Electricity' },
  { vendor_id: 1197, fuel_type: 'Electricity' },
  { vendor_id: 1198, fuel_type: 'Electricity' },
  { vendor_id: 1199, fuel_type: 'Electricity' },
  { vendor_id: 1200, fuel_type: 'Electricity' },
  { vendor_id: 1201, fuel_type: 'Electricity' },
  { vendor_id: 1202, fuel_type: 'Electricity' },
  { vendor_id: 1203, fuel_type: 'Electricity' },
  { vendor_id: 1205, fuel_type: 'Natural Gas' },
  { vendor_id: 1205, fuel_type: 'Electricity' },
  { vendor_id: 1206, fuel_type: 'Electricity' },
  { vendor_id: 1207, fuel_type: 'Electricity' },
  { vendor_id: 1208, fuel_type: 'Electricity' },
  { vendor_id: 1210, fuel_type: 'Electricity' },
  { vendor_id: 1211, fuel_type: 'Electricity' },
  { vendor_id: 1212, fuel_type: 'Electricity' },
  { vendor_id: 1213, fuel_type: 'Electricity' },
  { vendor_id: 1214, fuel_type: 'Electricity' },
  { vendor_id: 1215, fuel_type: 'Electricity' },
  { vendor_id: 1216, fuel_type: 'Natural Gas' },
  { vendor_id: 1216, fuel_type: 'Electricity' },
  { vendor_id: 1217, fuel_type: 'Electricity' },
  { vendor_id: 1218, fuel_type: 'Electricity' },
  { vendor_id: 1220, fuel_type: 'Electricity' },
  { vendor_id: 1221, fuel_type: 'Electricity' },
  { vendor_id: 1221, fuel_type: 'Natural Gas' },
  { vendor_id: 1222, fuel_type: 'Electricity' },
  { vendor_id: 1223, fuel_type: 'Electricity' },
  { vendor_id: 1224, fuel_type: 'Electricity' },
  { vendor_id: 1225, fuel_type: 'Electricity' },
  { vendor_id: 1227, fuel_type: 'Natural Gas' },
  { vendor_id: 1228, fuel_type: 'Natural Gas' },
  { vendor_id: 1229, fuel_type: 'Electricity' },
  { vendor_id: 1230, fuel_type: 'Electricity' },
  { vendor_id: 1233, fuel_type: 'Oil' },
  { vendor_id: 1233, fuel_type: 'Biofuel' },
  { vendor_id: 1234, fuel_type: 'Propane / LP' },
  { vendor_id: 1237, fuel_type: 'Propane / LP' },
  { vendor_id: 1237, fuel_type: 'Oil' },
  { vendor_id: 1238, fuel_type: 'Propane / LP' },
  { vendor_id: 1238, fuel_type: 'Oil' },
  { vendor_id: 1239, fuel_type: 'Natural Gas' },
  { vendor_id: 1239, fuel_type: 'Propane / LP' },
  { vendor_id: 1239, fuel_type: 'Oil' },
  { vendor_id: 1240, fuel_type: 'Oil' },
  { vendor_id: 1241, fuel_type: 'Natural Gas' },
  { vendor_id: 1242, fuel_type: 'Propane / LP' },
  { vendor_id: 1243, fuel_type: 'Propane / LP' },
  { vendor_id: 1243, fuel_type: 'Oil' },
  { vendor_id: 1244, fuel_type: 'Electricity' },
  { vendor_id: 1248, fuel_type: 'Propane / LP' },
  { vendor_id: 1249, fuel_type: 'Propane / LP' },
  { vendor_id: 1249, fuel_type: 'Oil' },
  { vendor_id: 1250, fuel_type: 'Oil' },
  { vendor_id: 1252, fuel_type: 'Oil' },
  { vendor_id: 1252, fuel_type: 'Propane / LP' },
  { vendor_id: 1253, fuel_type: 'Oil' },
  { vendor_id: 1254, fuel_type: 'Propane / LP' },
  { vendor_id: 1257, fuel_type: 'Propane / LP' },
  { vendor_id: 1259, fuel_type: 'Oil' },
  { vendor_id: 1259, fuel_type: 'Propane / LP' },
  { vendor_id: 1261, fuel_type: 'Propane / LP' },
  { vendor_id: 1265, fuel_type: 'Oil' },
  { vendor_id: 1267, fuel_type: 'Oil' },
  { vendor_id: 1268, fuel_type: 'Propane / LP' },
  { vendor_id: 1269, fuel_type: 'Propane / LP' },
  { vendor_id: 1271, fuel_type: 'Electricity' },
  { vendor_id: 1272, fuel_type: 'Propane / LP' },
  { vendor_id: 1273, fuel_type: 'Propane / LP' },
  { vendor_id: 1273, fuel_type: 'Oil' },
  { vendor_id: 1274, fuel_type: 'Oil' },
  { vendor_id: 1276, fuel_type: 'Wood' },
  { vendor_id: 1277, fuel_type: 'Oil' },
  { vendor_id: 1277, fuel_type: 'Propane / LP' },
  { vendor_id: 1280, fuel_type: 'Electricity' },
  { vendor_id: 1285, fuel_type: 'Oil' },
  { vendor_id: 1286, fuel_type: 'Propane / LP' },
  { vendor_id: 1287, fuel_type: 'Propane / LP' },
  { vendor_id: 1289, fuel_type: 'Oil' },
  { vendor_id: 1293, fuel_type: 'Wood' },
  { vendor_id: 1295, fuel_type: 'Oil' },
  { vendor_id: 1296, fuel_type: 'Oil' },
  { vendor_id: 1296, fuel_type: 'Propane / LP' },
  { vendor_id: 1297, fuel_type: 'Propane / LP' },
  { vendor_id: 1298, fuel_type: 'Oil' },
  { vendor_id: 1299, fuel_type: 'Oil' },
  { vendor_id: 1300, fuel_type: 'Oil' },
  { vendor_id: 1301, fuel_type: 'Propane / LP' },
  { vendor_id: 1303, fuel_type: 'Propane / LP' },
  { vendor_id: 1304, fuel_type: 'Propane / LP' },
  { vendor_id: 1305, fuel_type: 'Oil' },
  { vendor_id: 1306, fuel_type: 'St.Paul Dist.Htg' },
  { vendor_id: 1307, fuel_type: 'Oil' },
  { vendor_id: 1309, fuel_type: 'Propane / LP' },
  { vendor_id: 1309, fuel_type: 'Oil' },
  { vendor_id: 1312, fuel_type: 'Oil' },
  { vendor_id: 1315, fuel_type: 'Wood' },
  { vendor_id: 1320, fuel_type: 'Propane / LP' },
  { vendor_id: 1321, fuel_type: 'Electricity' },
  { vendor_id: 1322, fuel_type: 'Natural Gas' },
  { vendor_id: 1323, fuel_type: 'Electricity' },
  { vendor_id: 1324, fuel_type: 'Propane / LP' },
  { vendor_id: 1325, fuel_type: 'Oil' },
  { vendor_id: 1327, fuel_type: 'Propane / LP' },
  { vendor_id: 1328, fuel_type: 'Wood' },
  { vendor_id: 1330, fuel_type: 'Propane / LP' },
  { vendor_id: 1330, fuel_type: 'Oil' },
  { vendor_id: 1331, fuel_type: 'Oil' },
  { vendor_id: 1332, fuel_type: 'Propane / LP' },
  { vendor_id: 1333, fuel_type: 'Electricity' },
  { vendor_id: 1335, fuel_type: 'Electricity' },
  { vendor_id: 1336, fuel_type: 'Propane / LP' },
  { vendor_id: 1338, fuel_type: 'Wood' },
  { vendor_id: 1342, fuel_type: 'Oil' },
  { vendor_id: 1344, fuel_type: 'Propane / LP' },
  { vendor_id: 1345, fuel_type: 'Propane / LP' },
  { vendor_id: 1346, fuel_type: 'Oil' },
  { vendor_id: 1347, fuel_type: 'Propane / LP' },
  { vendor_id: 1348, fuel_type: 'Propane / LP' },
  { vendor_id: 1351, fuel_type: 'Propane / LP' },
  { vendor_id: 1351, fuel_type: 'Oil' },
  { vendor_id: 1352, fuel_type: 'Oil' },
  { vendor_id: 1352, fuel_type: 'Propane / LP' },
  { vendor_id: 1353, fuel_type: 'Oil' },
  { vendor_id: 1353, fuel_type: 'Propane / LP' },
  { vendor_id: 1354, fuel_type: 'Propane / LP' },
  { vendor_id: 1354, fuel_type: 'Oil' },
  { vendor_id: 1355, fuel_type: 'Propane / LP' },
  { vendor_id: 1356, fuel_type: 'Propane / LP' },
  { vendor_id: 1356, fuel_type: 'Oil' },
  { vendor_id: 1358, fuel_type: 'Propane / LP' },
  { vendor_id: 1359, fuel_type: 'Propane / LP' },
  { vendor_id: 1360, fuel_type: 'Propane / LP' },
  { vendor_id: 1360, fuel_type: 'Oil' },
  { vendor_id: 1364, fuel_type: 'Propane / LP' },
  { vendor_id: 1365, fuel_type: 'Oil' },
  { vendor_id: 1367, fuel_type: 'Propane / LP' },
  { vendor_id: 1371, fuel_type: 'Propane / LP' },
  { vendor_id: 1371, fuel_type: 'Oil' },
  { vendor_id: 1372, fuel_type: 'Oil' },
  { vendor_id: 1376, fuel_type: 'Propane / LP' },
  { vendor_id: 1376, fuel_type: 'Oil' },
  { vendor_id: 1378, fuel_type: 'Propane / LP' },
  { vendor_id: 1378, fuel_type: 'Oil' },
  { vendor_id: 1379, fuel_type: 'Propane / LP' },
  { vendor_id: 1381, fuel_type: 'Propane / LP' },
  { vendor_id: 1383, fuel_type: 'Oil' },
  { vendor_id: 1384, fuel_type: 'Oil' },
  { vendor_id: 1384, fuel_type: 'Propane / LP' },
  { vendor_id: 1386, fuel_type: 'Oil' },
  { vendor_id: 1386, fuel_type: 'Propane / LP' },
  { vendor_id: 1387, fuel_type: 'Propane / LP' },
  { vendor_id: 1387, fuel_type: 'Oil' },
  { vendor_id: 1390, fuel_type: 'Propane / LP' },
  { vendor_id: 1390, fuel_type: 'Oil' },
  { vendor_id: 1391, fuel_type: 'Electricity' },
  { vendor_id: 1392, fuel_type: 'Propane / LP' },
  { vendor_id: 1392, fuel_type: 'Oil' },
  { vendor_id: 1420, fuel_type: 'Propane / LP' },
  { vendor_id: 1425, fuel_type: 'Propane / LP' },
  { vendor_id: 1425, fuel_type: 'Oil' },
  { vendor_id: 1427, fuel_type: 'Oil' },
  { vendor_id: 1428, fuel_type: 'Propane / LP' },
  { vendor_id: 1429, fuel_type: 'Propane / LP' },
  { vendor_id: 1430, fuel_type: 'Oil' },
  { vendor_id: 1433, fuel_type: 'Propane / LP' },
  { vendor_id: 1434, fuel_type: 'Propane / LP' },
  { vendor_id: 1437, fuel_type: 'Propane / LP' },
  { vendor_id: 1438, fuel_type: 'Oil' },
  { vendor_id: 1439, fuel_type: 'Natural Gas' },
  { vendor_id: 1439, fuel_type: 'Electricity' },
  { vendor_id: 1441, fuel_type: 'Oil' },
  { vendor_id: 1442, fuel_type: 'Oil' },
  { vendor_id: 1443, fuel_type: 'Propane / LP' },
  { vendor_id: 1446, fuel_type: 'Propane / LP' },
  { vendor_id: 1447, fuel_type: 'Oil' },
  { vendor_id: 1447, fuel_type: 'Propane / LP' },
  { vendor_id: 1449, fuel_type: 'Electricity' },
  { vendor_id: 1452, fuel_type: 'Oil' },
  { vendor_id: 1453, fuel_type: 'Oil' },
  { vendor_id: 1455, fuel_type: 'Propane / LP' },
  { vendor_id: 1457, fuel_type: 'Propane / LP' },
  { vendor_id: 1457, fuel_type: 'Oil' },
  { vendor_id: 1458, fuel_type: 'Wood' },
  { vendor_id: 1460, fuel_type: 'Propane / LP' },
  { vendor_id: 1461, fuel_type: 'Propane / LP' },
  { vendor_id: 1461, fuel_type: 'Oil' },
  { vendor_id: 1462, fuel_type: 'Propane / LP' },
  { vendor_id: 1463, fuel_type: 'Propane / LP' },
  { vendor_id: 1464, fuel_type: 'Propane / LP' },
  { vendor_id: 1466, fuel_type: 'Propane / LP' },
  { vendor_id: 1468, fuel_type: 'Propane / LP' },
  { vendor_id: 1470, fuel_type: 'Propane / LP' },
  { vendor_id: 1470, fuel_type: 'Oil' },
  { vendor_id: 1472, fuel_type: 'Oil' },
  { vendor_id: 1473, fuel_type: 'Propane / LP' },
  { vendor_id: 1475, fuel_type: 'Oil' },
  { vendor_id: 1477, fuel_type: 'Oil' },
  { vendor_id: 1478, fuel_type: 'Electricity' },
  { vendor_id: 1479, fuel_type: 'Natural Gas' },
  { vendor_id: 1480, fuel_type: 'Electricity' },
  { vendor_id: 1482, fuel_type: 'Electricity' },
  { vendor_id: 1488, fuel_type: 'Natural Gas' },
  { vendor_id: 1494, fuel_type: 'Natural Gas' },
  { vendor_id: 1496, fuel_type: 'Propane / LP' },
  { vendor_id: 1496, fuel_type: 'Oil' },
  { vendor_id: 1497, fuel_type: 'Oil' },
  { vendor_id: 1498, fuel_type: 'Oil' },
  { vendor_id: 1498, fuel_type: 'Propane / LP' },
  { vendor_id: 1499, fuel_type: 'Oil' },
  { vendor_id: 1500, fuel_type: 'Propane / LP' },
  { vendor_id: 1503, fuel_type: 'Oil' },
  { vendor_id: 1504, fuel_type: 'Oil' },
  { vendor_id: 1504, fuel_type: 'Propane / LP' },
  { vendor_id: 1505, fuel_type: 'Electricity' },
  { vendor_id: 1506, fuel_type: 'Oil' },
  { vendor_id: 1507, fuel_type: 'Propane / LP' },
  { vendor_id: 1507, fuel_type: 'Oil' },
  { vendor_id: 1509, fuel_type: 'Propane / LP' },
  { vendor_id: 1510, fuel_type: 'Oil' },
  { vendor_id: 1511, fuel_type: 'Oil' },
  { vendor_id: 1512, fuel_type: 'Propane / LP' },
  { vendor_id: 1514, fuel_type: 'Propane / LP' },
  { vendor_id: 1514, fuel_type: 'Oil' },
  { vendor_id: 1515, fuel_type: 'Wood' },
  { vendor_id: 1516, fuel_type: 'Propane / LP' },
  { vendor_id: 1518, fuel_type: 'Electricity' },
  { vendor_id: 1522, fuel_type: 'Propane / LP' },
  { vendor_id: 1524, fuel_type: 'Propane / LP' },
  { vendor_id: 1526, fuel_type: 'Oil' },
  { vendor_id: 1529, fuel_type: 'Propane / LP' },
  { vendor_id: 1530, fuel_type: 'Propane / LP' },
  { vendor_id: 1531, fuel_type: 'Oil' },
  { vendor_id: 1531, fuel_type: 'Propane / LP' },
  { vendor_id: 1535, fuel_type: 'Wood' },
  { vendor_id: 1539, fuel_type: 'Oil' },
  { vendor_id: 1541, fuel_type: 'Oil' },
  { vendor_id: 1543, fuel_type: 'Oil' },
  { vendor_id: 1544, fuel_type: 'Oil' },
  { vendor_id: 1545, fuel_type: 'Propane / LP' },
  { vendor_id: 1545, fuel_type: 'Oil' },
  { vendor_id: 1548, fuel_type: 'Propane / LP' },
  { vendor_id: 1549, fuel_type: 'Oil' },
  { vendor_id: 1550, fuel_type: 'Oil' },
  { vendor_id: 1552, fuel_type: 'Propane / LP' },
  { vendor_id: 1552, fuel_type: 'Oil' },
  { vendor_id: 1553, fuel_type: 'Propane / LP' },
  { vendor_id: 1554, fuel_type: 'Oil' },
  { vendor_id: 1555, fuel_type: 'Electricity' },
  { vendor_id: 1557, fuel_type: 'Propane / LP' },
  { vendor_id: 1559, fuel_type: 'Oil' },
  { vendor_id: 1559, fuel_type: 'Propane / LP' },
  { vendor_id: 1560, fuel_type: 'Natural Gas' },
  { vendor_id: 1560, fuel_type: 'Electricity' },
  { vendor_id: 1561, fuel_type: 'Propane / LP' },
  { vendor_id: 1561, fuel_type: 'Oil' },
  { vendor_id: 1562, fuel_type: 'Propane / LP' },
  { vendor_id: 1563, fuel_type: 'Oil' },
  { vendor_id: 1563, fuel_type: 'Propane / LP' },
  { vendor_id: 1581, fuel_type: 'Propane / LP' },
  { vendor_id: 1582, fuel_type: 'Wood' },
  { vendor_id: 1583, fuel_type: 'Electricity' },
  { vendor_id: 1586, fuel_type: 'Oil' },
  { vendor_id: 1588, fuel_type: 'Oil' },
  { vendor_id: 1588, fuel_type: 'Propane / LP' },
  { vendor_id: 1589, fuel_type: 'Electricity' },
  { vendor_id: 1595, fuel_type: 'Propane / LP' },
  { vendor_id: 1595, fuel_type: 'Oil' },
  { vendor_id: 1597, fuel_type: 'Propane / LP' },
  { vendor_id: 1598, fuel_type: 'Wood' },
  { vendor_id: 1599, fuel_type: 'Wood' },
  { vendor_id: 1601, fuel_type: 'Oil' },
  { vendor_id: 1605, fuel_type: 'Propane / LP' },
  { vendor_id: 1609, fuel_type: 'Electricity' },
  { vendor_id: 1610, fuel_type: 'Oil' },
  { vendor_id: 1615, fuel_type: 'Wood' },
  { vendor_id: 1616, fuel_type: 'Propane / LP' },
  { vendor_id: 1618, fuel_type: 'Electricity' },
  { vendor_id: 1619, fuel_type: 'Oil' },
  { vendor_id: 1621, fuel_type: 'Oil' },
  { vendor_id: 1623, fuel_type: 'Oil' },
  { vendor_id: 1624, fuel_type: 'Propane / LP' },
  { vendor_id: 1625, fuel_type: 'Oil' },
  { vendor_id: 1628, fuel_type: 'Oil' },
  { vendor_id: 1628, fuel_type: 'Propane / LP' },
  { vendor_id: 1630, fuel_type: 'Propane / LP' },
  { vendor_id: 1631, fuel_type: 'Oil' },
  { vendor_id: 1633, fuel_type: 'Oil' },
  { vendor_id: 1634, fuel_type: 'Oil' },
  { vendor_id: 1635, fuel_type: 'Oil' },
  { vendor_id: 1636, fuel_type: 'Oil' },
  { vendor_id: 1637, fuel_type: 'Propane / LP' },
  { vendor_id: 1639, fuel_type: 'Propane / LP' },
  { vendor_id: 1640, fuel_type: 'Oil' },
  { vendor_id: 1641, fuel_type: 'Oil' },
  { vendor_id: 1642, fuel_type: 'Oil' },
  { vendor_id: 1643, fuel_type: 'Oil' },
  { vendor_id: 1645, fuel_type: 'Oil' },
  { vendor_id: 1645, fuel_type: 'Propane / LP' },
  { vendor_id: 1646, fuel_type: 'Oil' },
  { vendor_id: 1647, fuel_type: 'Electricity' },
  { vendor_id: 1648, fuel_type: 'Electricity' },
  { vendor_id: 1650, fuel_type: 'Electricity' },
  { vendor_id: 1652, fuel_type: 'Oil' },
  { vendor_id: 1654, fuel_type: 'Natural Gas' },
  { vendor_id: 1654, fuel_type: 'Electricity' },
  { vendor_id: 1655, fuel_type: 'Propane / LP' },
  { vendor_id: 1657, fuel_type: 'Electricity' },
  { vendor_id: 1659, fuel_type: 'Propane / LP' },
  { vendor_id: 1660, fuel_type: 'Electricity' },
  { vendor_id: 1661, fuel_type: 'Propane / LP' },
  { vendor_id: 1663, fuel_type: 'Propane / LP' },
  { vendor_id: 1664, fuel_type: 'Propane / LP' },
  { vendor_id: 1667, fuel_type: 'Propane / LP' },
  { vendor_id: 1668, fuel_type: 'Propane / LP' },
  { vendor_id: 1669, fuel_type: 'Propane / LP' },
  { vendor_id: 1670, fuel_type: 'Propane / LP' },
  { vendor_id: 1674, fuel_type: 'Propane / LP' },
  { vendor_id: 1675, fuel_type: 'Propane / LP' },
  { vendor_id: 1676, fuel_type: 'Propane / LP' },
  { vendor_id: 1677, fuel_type: 'Propane / LP' },
  { vendor_id: 1678, fuel_type: 'Propane / LP' },
  { vendor_id: 1679, fuel_type: 'Propane / LP' },
  { vendor_id: 1680, fuel_type: 'Propane / LP' },
  { vendor_id: 1681, fuel_type: 'Propane / LP' },
  { vendor_id: 1682, fuel_type: 'Propane / LP' },
  { vendor_id: 1683, fuel_type: 'Propane / LP' },
  { vendor_id: 1684, fuel_type: 'Propane / LP' },
  { vendor_id: 1685, fuel_type: 'Propane / LP' },
  { vendor_id: 1686, fuel_type: 'Propane / LP' },
  { vendor_id: 1687, fuel_type: 'Propane / LP' },
  { vendor_id: 1688, fuel_type: 'Propane / LP' },
  { vendor_id: 1689, fuel_type: 'Propane / LP' },
  { vendor_id: 1690, fuel_type: 'Propane / LP' },
  { vendor_id: 1692, fuel_type: 'Propane / LP' },
  { vendor_id: 1693, fuel_type: 'Propane / LP' },
  { vendor_id: 1693, fuel_type: 'Oil' },
  { vendor_id: 1694, fuel_type: 'Electricity' },
  { vendor_id: 1696, fuel_type: 'Oil' },
  { vendor_id: 1697, fuel_type: 'Wood' },
  { vendor_id: 1699, fuel_type: 'Propane / LP' },
  { vendor_id: 1700, fuel_type: 'Oil' },
  { vendor_id: 1700, fuel_type: 'Propane / LP' },
  { vendor_id: 1701, fuel_type: 'Propane / LP' },
  { vendor_id: 1703, fuel_type: 'Wood' },
  { vendor_id: 1704, fuel_type: 'Oil' },
  { vendor_id: 1706, fuel_type: 'Oil' },
  { vendor_id: 1707, fuel_type: 'Oil' },
  { vendor_id: 1708, fuel_type: 'Propane / LP' },
  { vendor_id: 1711, fuel_type: 'Propane / LP' },
  { vendor_id: 1713, fuel_type: 'Electricity' },
  { vendor_id: 1715, fuel_type: 'Oil' },
  { vendor_id: 1716, fuel_type: 'Oil' },
  { vendor_id: 1717, fuel_type: 'Oil' },
  { vendor_id: 1718, fuel_type: 'Wood' },
  { vendor_id: 1719, fuel_type: 'Oil' },
  { vendor_id: 1721, fuel_type: 'Propane / LP' },
  { vendor_id: 1722, fuel_type: 'Wood' },
  { vendor_id: 1725, fuel_type: 'Electricity' },
  { vendor_id: 1727, fuel_type: 'Oil' },
  { vendor_id: 1730, fuel_type: 'Electricity' },
  { vendor_id: 1731, fuel_type: 'Electricity' },
  { vendor_id: 1732, fuel_type: 'Oil' },
  { vendor_id: 1738, fuel_type: 'Propane / LP' },
  { vendor_id: 1740, fuel_type: 'Propane / LP' },
  { vendor_id: 1740, fuel_type: 'Oil' },
  { vendor_id: 1741, fuel_type: 'Electricity' },
  { vendor_id: 1742, fuel_type: 'Oil' },
  { vendor_id: 1744, fuel_type: 'Oil' },
  { vendor_id: 1747, fuel_type: 'Oil' },
  { vendor_id: 1748, fuel_type: 'Propane / LP' },
  { vendor_id: 1751, fuel_type: 'Oil' },
  { vendor_id: 1752, fuel_type: 'Electricity' },
  { vendor_id: 1753, fuel_type: 'Propane / LP' },
  { vendor_id: 1753, fuel_type: 'Oil' },
  { vendor_id: 1754, fuel_type: 'Oil' },
  { vendor_id: 1754, fuel_type: 'Propane / LP' },
  { vendor_id: 1756, fuel_type: 'Electricity' },
  { vendor_id: 1757, fuel_type: 'Oil' },
  { vendor_id: 1759, fuel_type: 'Oil' },
  { vendor_id: 1761, fuel_type: 'Electricity' },
  { vendor_id: 1765, fuel_type: 'Propane / LP' },
  { vendor_id: 1767, fuel_type: 'Wood' },
  { vendor_id: 1768, fuel_type: 'Oil' },
  { vendor_id: 1768, fuel_type: 'Propane / LP' },
  { vendor_id: 1770, fuel_type: 'Propane / LP' },
  { vendor_id: 1772, fuel_type: 'Propane / LP' },
  { vendor_id: 1773, fuel_type: 'Propane / LP' },
  { vendor_id: 1776, fuel_type: 'Propane / LP' },
  { vendor_id: 1776, fuel_type: 'Oil' },
  { vendor_id: 1777, fuel_type: 'Oil' },
  { vendor_id: 1781, fuel_type: 'Electricity' },
  { vendor_id: 1782, fuel_type: 'Oil' },
  { vendor_id: 1783, fuel_type: 'Electricity' },
  { vendor_id: 1784, fuel_type: 'Electricity' },
  { vendor_id: 1785, fuel_type: 'Electricity' },
  { vendor_id: 1787, fuel_type: 'Propane / LP' },
  { vendor_id: 1787, fuel_type: 'Oil' },
  { vendor_id: 1789, fuel_type: 'Propane / LP' },
  { vendor_id: 1791, fuel_type: 'Propane / LP' },
  { vendor_id: 1793, fuel_type: 'Oil' },
  { vendor_id: 1794, fuel_type: 'Oil' },
  { vendor_id: 1795, fuel_type: 'Propane / LP' },
  { vendor_id: 1796, fuel_type: 'Oil' },
  { vendor_id: 1797, fuel_type: 'Electricity' },
  { vendor_id: 1798, fuel_type: 'Electricity' },
  { vendor_id: 1799, fuel_type: 'Propane / LP' },
  { vendor_id: 1799, fuel_type: 'Oil' },
  { vendor_id: 1801, fuel_type: 'Natural Gas' },
  { vendor_id: 1802, fuel_type: 'Oil' },
  { vendor_id: 1804, fuel_type: 'Oil' },
  { vendor_id: 1804, fuel_type: 'Propane / LP' },
  { vendor_id: 1806, fuel_type: 'Electricity' },
  { vendor_id: 1807, fuel_type: 'Electricity' },
  { vendor_id: 1808, fuel_type: 'Electricity' },
  { vendor_id: 1809, fuel_type: 'Oil' },
  { vendor_id: 1810, fuel_type: 'Propane / LP' },
  { vendor_id: 1810, fuel_type: 'Oil' },
  { vendor_id: 1812, fuel_type: 'Oil' },
  { vendor_id: 1813, fuel_type: 'Propane / LP' },
  { vendor_id: 1818, fuel_type: 'Propane / LP' },
  { vendor_id: 1819, fuel_type: 'Propane / LP' },
  { vendor_id: 1824, fuel_type: 'Propane / LP' },
  { vendor_id: 1825, fuel_type: 'Propane / LP' },
  { vendor_id: 1827, fuel_type: 'Propane / LP' },
  { vendor_id: 1828, fuel_type: 'Oil' },
  { vendor_id: 1828, fuel_type: 'Propane / LP' },
  { vendor_id: 1830, fuel_type: 'Wood' },
  { vendor_id: 1831, fuel_type: 'Oil' },
  { vendor_id: 1833, fuel_type: 'Propane / LP' },
  { vendor_id: 1833, fuel_type: 'Oil' },
  { vendor_id: 1833, fuel_type: 'Metered Propane/LP' },
  { vendor_id: 1834, fuel_type: 'Propane / LP' },
  { vendor_id: 1835, fuel_type: 'Oil' },
  { vendor_id: 1836, fuel_type: 'Propane / LP' },
  { vendor_id: 1838, fuel_type: 'Oil' },
  { vendor_id: 1840, fuel_type: 'Natural Gas' },
  { vendor_id: 1840, fuel_type: 'Electricity' },
  { vendor_id: 1840, fuel_type: 'Muni.Steam' },
  { vendor_id: 1841, fuel_type: 'Natural Gas' },
  { vendor_id: 1842, fuel_type: 'Oil' },
  { vendor_id: 1843, fuel_type: 'Oil' },
  { vendor_id: 1844, fuel_type: 'Oil' },
  { vendor_id: 1846, fuel_type: 'Propane / LP' },
  { vendor_id: 1849, fuel_type: 'Electricity' },
  { vendor_id: 1850, fuel_type: 'Oil' },
  { vendor_id: 1850, fuel_type: 'Propane / LP' },
  { vendor_id: 1851, fuel_type: 'Oil' },
  { vendor_id: 1851, fuel_type: 'Propane / LP' },
  { vendor_id: 1852, fuel_type: 'Oil' },
  { vendor_id: 1853, fuel_type: 'Electricity' },
  { vendor_id: 1855, fuel_type: 'Electricity' },
  { vendor_id: 1856, fuel_type: 'Propane / LP' },
  { vendor_id: 1856, fuel_type: 'Oil' },
  { vendor_id: 1857, fuel_type: 'Electricity' },
  { vendor_id: 1859, fuel_type: 'Oil' },
  { vendor_id: 1861, fuel_type: 'Propane / LP' },
  { vendor_id: 1862, fuel_type: 'Propane / LP' },
  { vendor_id: 1862, fuel_type: 'Oil' },
  { vendor_id: 1868, fuel_type: 'Propane / LP' },
  { vendor_id: 1868, fuel_type: 'Oil' },
  { vendor_id: 1870, fuel_type: 'Oil' },
  { vendor_id: 1871, fuel_type: 'Propane / LP' },
  { vendor_id: 1872, fuel_type: 'Natural Gas' },
  { vendor_id: 1873, fuel_type: 'Electricity' },
  { vendor_id: 1875, fuel_type: 'Propane / LP' },
  { vendor_id: 1875, fuel_type: 'Oil' },
  { vendor_id: 1876, fuel_type: 'Oil' },
  { vendor_id: 1878, fuel_type: 'Propane / LP' },
  { vendor_id: 1880, fuel_type: 'Oil' },
  { vendor_id: 1881, fuel_type: 'Propane / LP' },
  { vendor_id: 1881, fuel_type: 'Oil' },
  { vendor_id: 1882, fuel_type: 'Oil' },
  { vendor_id: 1882, fuel_type: 'Propane / LP' },
  { vendor_id: 1883, fuel_type: 'Oil' },
  { vendor_id: 1885, fuel_type: 'Oil' },
  { vendor_id: 1886, fuel_type: 'Electricity' },
  { vendor_id: 1887, fuel_type: 'Oil' },
  { vendor_id: 1888, fuel_type: 'Propane / LP' },
  { vendor_id: 1891, fuel_type: 'Electricity' },
  { vendor_id: 1895, fuel_type: 'Natural Gas' },
  { vendor_id: 1895, fuel_type: 'Electricity' },
  { vendor_id: 1896, fuel_type: 'Propane / LP' },
  { vendor_id: 1896, fuel_type: 'Oil' },
  { vendor_id: 1897, fuel_type: 'Oil' },
  { vendor_id: 1898, fuel_type: 'Oil' },
  { vendor_id: 1900, fuel_type: 'Propane / LP' },
  { vendor_id: 1900, fuel_type: 'Oil' },
  { vendor_id: 1901, fuel_type: 'Propane / LP' },
  { vendor_id: 1904, fuel_type: 'Propane / LP' },
  { vendor_id: 1904, fuel_type: 'Oil' },
  { vendor_id: 1905, fuel_type: 'Oil' },
  { vendor_id: 1906, fuel_type: 'Oil' },
  { vendor_id: 1910, fuel_type: 'Electricity' },
  { vendor_id: 1911, fuel_type: 'Natural Gas' },
  { vendor_id: 1914, fuel_type: 'Oil' },
  { vendor_id: 1915, fuel_type: 'Natural Gas' },
  { vendor_id: 1916, fuel_type: 'Propane / LP' },
  { vendor_id: 1916, fuel_type: 'Oil' },
  { vendor_id: 1917, fuel_type: 'Oil' },
  { vendor_id: 1924, fuel_type: 'Electricity' },
  { vendor_id: 1927, fuel_type: 'Propane / LP' },
  { vendor_id: 1928, fuel_type: 'Propane / LP' },
  { vendor_id: 1929, fuel_type: 'Electricity' },
  { vendor_id: 1932, fuel_type: 'Oil' },
  { vendor_id: 1934, fuel_type: 'Propane / LP' },
  { vendor_id: 1934, fuel_type: 'Oil' },
  { vendor_id: 1935, fuel_type: 'Propane / LP' },
  { vendor_id: 1939, fuel_type: 'Propane / LP' },
  { vendor_id: 1939, fuel_type: 'Oil' },
  { vendor_id: 1940, fuel_type: 'Natural Gas' },
  { vendor_id: 1942, fuel_type: 'Electricity' },
  { vendor_id: 1943, fuel_type: 'Electricity' },
  { vendor_id: 1945, fuel_type: 'Propane / LP' },
  { vendor_id: 1945, fuel_type: 'Oil' },
  { vendor_id: 1946, fuel_type: 'Oil' },
  { vendor_id: 1947, fuel_type: 'Electricity' },
  { vendor_id: 1948, fuel_type: 'Electricity' },
  { vendor_id: 1949, fuel_type: 'Wood' },
  { vendor_id: 1950, fuel_type: 'Propane / LP' },
  { vendor_id: 1951, fuel_type: 'Oil' },
  { vendor_id: 1954, fuel_type: 'Propane / LP' },
  { vendor_id: 1956, fuel_type: 'Natural Gas' },
  { vendor_id: 1956, fuel_type: 'Electricity' },
  { vendor_id: 1958, fuel_type: 'Propane / LP' },
  { vendor_id: 1959, fuel_type: 'Propane / LP' },
  { vendor_id: 1960, fuel_type: 'Oil' },
  { vendor_id: 1961, fuel_type: 'Oil' },
  { vendor_id: 1964, fuel_type: 'Oil' },
  { vendor_id: 1966, fuel_type: 'Propane / LP' },
  { vendor_id: 1966, fuel_type: 'Oil' },
  { vendor_id: 1967, fuel_type: 'Electricity' },
  { vendor_id: 1968, fuel_type: 'Electricity' },
  { vendor_id: 1969, fuel_type: 'Electricity' },
  { vendor_id: 1970, fuel_type: 'Electricity' },
  { vendor_id: 1973, fuel_type: 'Natural Gas' },
  { vendor_id: 1975, fuel_type: 'Propane / LP' },
  { vendor_id: 1976, fuel_type: 'Wood' },
  { vendor_id: 1978, fuel_type: 'Propane / LP' },
  { vendor_id: 1979, fuel_type: 'Electricity' },
  { vendor_id: 1986, fuel_type: 'Wood' },
  { vendor_id: 1989, fuel_type: 'Electricity' },
  { vendor_id: 1992, fuel_type: 'Propane / LP' },
  { vendor_id: 1995, fuel_type: 'Electricity' },
  { vendor_id: 1997, fuel_type: 'Oil' },
  { vendor_id: 2000, fuel_type: 'Propane / LP' },
  { vendor_id: 2001, fuel_type: 'Propane / LP' },
  { vendor_id: 2002, fuel_type: 'Electricity' },
  { vendor_id: 2003, fuel_type: 'Oil' },
  { vendor_id: 2007, fuel_type: 'Electricity' },
  { vendor_id: 2008, fuel_type: 'Oil' },
  { vendor_id: 2009, fuel_type: 'Propane / LP' },
  { vendor_id: 2015, fuel_type: 'Oil' },
  { vendor_id: 2016, fuel_type: 'Oil' },
  { vendor_id: 2017, fuel_type: 'Oil' },
  { vendor_id: 2018, fuel_type: 'Oil' },
  { vendor_id: 2019, fuel_type: 'Propane / LP' },
  { vendor_id: 2020, fuel_type: 'Oil' },
  { vendor_id: 2022, fuel_type: 'Electricity' },
  { vendor_id: 2023, fuel_type: 'Propane / LP' },
  { vendor_id: 2024, fuel_type: 'Oil' },
  { vendor_id: 2025, fuel_type: 'Propane / LP' },
  { vendor_id: 2028, fuel_type: 'Propane / LP' },
  { vendor_id: 2030, fuel_type: 'Oil' },
  { vendor_id: 2033, fuel_type: 'Oil' },
  { vendor_id: 2034, fuel_type: 'Propane / LP' },
  { vendor_id: 2034, fuel_type: 'Oil' },
  { vendor_id: 2035, fuel_type: 'Electricity' },
  { vendor_id: 2036, fuel_type: 'Natural Gas' },
  { vendor_id: 2036, fuel_type: 'Propane / LP' },
  { vendor_id: 2041, fuel_type: 'Propane / LP' },
  { vendor_id: 2041, fuel_type: 'Oil' },
  { vendor_id: 2042, fuel_type: 'Electricity' },
  { vendor_id: 2043, fuel_type: 'Propane / LP' },
  { vendor_id: 2044, fuel_type: 'Oil' },
  { vendor_id: 2045, fuel_type: 'Propane / LP' },
  { vendor_id: 2047, fuel_type: 'Propane / LP' },
  { vendor_id: 2050, fuel_type: 'Propane / LP' },
  { vendor_id: 2051, fuel_type: 'Oil' },
  { vendor_id: 2052, fuel_type: 'Propane / LP' },
  { vendor_id: 2054, fuel_type: 'Electricity' },
  { vendor_id: 2057, fuel_type: 'Propane / LP' },
  { vendor_id: 2060, fuel_type: 'Wood' },
  { vendor_id: 2061, fuel_type: 'Electricity' },
  { vendor_id: 2062, fuel_type: 'Electricity' },
  { vendor_id: 2063, fuel_type: 'Propane / LP' },
  { vendor_id: 2065, fuel_type: 'Propane / LP' },
  { vendor_id: 2068, fuel_type: 'Wood' },
  { vendor_id: 2069, fuel_type: 'Oil' },
  { vendor_id: 2070, fuel_type: 'Propane / LP' },
  { vendor_id: 2071, fuel_type: 'Oil' },
  { vendor_id: 2072, fuel_type: 'Propane / LP' },
  { vendor_id: 2072, fuel_type: 'Electricity' },
  { vendor_id: 2073, fuel_type: 'Electricity' },
  { vendor_id: 2074, fuel_type: 'Wood' },
  { vendor_id: 2075, fuel_type: 'Oil' },
  { vendor_id: 2076, fuel_type: 'Oil' },
  { vendor_id: 2078, fuel_type: 'Oil' },
  { vendor_id: 2079, fuel_type: 'Oil' },
  { vendor_id: 2081, fuel_type: 'Propane / LP' },
  { vendor_id: 2082, fuel_type: 'Propane / LP' },
  { vendor_id: 2083, fuel_type: 'Propane / LP' },
  { vendor_id: 2084, fuel_type: 'Propane / LP' },
  { vendor_id: 2085, fuel_type: 'Propane / LP' },
  { vendor_id: 2086, fuel_type: 'Propane / LP' },
  { vendor_id: 2087, fuel_type: 'Propane / LP' },
  { vendor_id: 2088, fuel_type: 'Propane / LP' },
  { vendor_id: 2089, fuel_type: 'Propane / LP' },
  { vendor_id: 2090, fuel_type: 'Oil' },
  { vendor_id: 2091, fuel_type: 'Oil' },
  { vendor_id: 2092, fuel_type: 'Propane / LP' },
  { vendor_id: 2095, fuel_type: 'Oil' },
  { vendor_id: 2106, fuel_type: 'Oil' },
  { vendor_id: 2107, fuel_type: 'Propane / LP' },
  { vendor_id: 2107, fuel_type: 'Oil' },
  { vendor_id: 2108, fuel_type: 'Oil' },
  { vendor_id: 2109, fuel_type: 'Propane / LP' },
  { vendor_id: 2110, fuel_type: 'Propane / LP' },
  { vendor_id: 2111, fuel_type: 'Oil' },
  { vendor_id: 2112, fuel_type: 'Electricity' },
  { vendor_id: 2113, fuel_type: 'Oil' },
  { vendor_id: 2114, fuel_type: 'Oil' },
  { vendor_id: 2116, fuel_type: 'Propane / LP' },
  { vendor_id: 2117, fuel_type: 'Propane / LP' },
  { vendor_id: 2117, fuel_type: 'Oil' },
  { vendor_id: 2118, fuel_type: 'Oil' },
  { vendor_id: 2119, fuel_type: 'Propane / LP' },
  { vendor_id: 2119, fuel_type: 'Metered Propane/LP' },
  { vendor_id: 2121, fuel_type: 'Electricity' },
  { vendor_id: 2122, fuel_type: 'Propane / LP' },
  { vendor_id: 2123, fuel_type: 'Propane / LP' },
  { vendor_id: 2124, fuel_type: 'Oil' },
  { vendor_id: 2124, fuel_type: 'Propane / LP' },
  { vendor_id: 2125, fuel_type: 'Oil' },
  { vendor_id: 2127, fuel_type: 'Oil' },
  { vendor_id: 2130, fuel_type: 'Electricity' },
  { vendor_id: 2132, fuel_type: 'Propane / LP' },
  { vendor_id: 2133, fuel_type: 'Propane / LP' },
  { vendor_id: 2133, fuel_type: 'Metered Propane/LP' },
  { vendor_id: 2136, fuel_type: 'Propane / LP' },
  { vendor_id: 2138, fuel_type: 'Natural Gas' },
  { vendor_id: 2138, fuel_type: 'Electricity' },
  { vendor_id: 2139, fuel_type: 'Oil' },
  { vendor_id: 2142, fuel_type: 'Propane / LP' },
  { vendor_id: 2142, fuel_type: 'Oil' },
  { vendor_id: 2144, fuel_type: 'Propane / LP' },
  { vendor_id: 2146, fuel_type: 'Propane / LP' },
  { vendor_id: 2148, fuel_type: 'Oil' },
  { vendor_id: 2150, fuel_type: 'Oil' },
  { vendor_id: 2151, fuel_type: 'Oil' },
  { vendor_id: 2153, fuel_type: 'Oil' },
  { vendor_id: 2155, fuel_type: 'Propane / LP' },
  { vendor_id: 2156, fuel_type: 'Oil' },
  { vendor_id: 2158, fuel_type: 'Oil' },
  { vendor_id: 2160, fuel_type: 'Oil' },
  { vendor_id: 2161, fuel_type: 'Wood' },
  { vendor_id: 2162, fuel_type: 'Wood' },
  { vendor_id: 2164, fuel_type: 'Propane / LP' },
  { vendor_id: 2166, fuel_type: 'Natural Gas' },
  { vendor_id: 2166, fuel_type: 'Electricity' },
  { vendor_id: 2166, fuel_type: 'Muni.Steam' },
  { vendor_id: 2168, fuel_type: 'Propane / LP' },
  { vendor_id: 2169, fuel_type: 'Propane / LP' },
  { vendor_id: 2170, fuel_type: 'Oil' },
  { vendor_id: 2172, fuel_type: 'Electricity' },
  { vendor_id: 2174, fuel_type: 'Propane / LP' },
  { vendor_id: 2181, fuel_type: 'Oil' },
  { vendor_id: 2182, fuel_type: 'Oil' },
  { vendor_id: 2183, fuel_type: 'Oil' },
  { vendor_id: 2185, fuel_type: 'Oil' },
  { vendor_id: 2186, fuel_type: 'Wood' },
  { vendor_id: 2187, fuel_type: 'Propane / LP' },
  { vendor_id: 2190, fuel_type: 'Propane / LP' },
  { vendor_id: 2191, fuel_type: 'Oil' },
  { vendor_id: 2192, fuel_type: 'Oil' },
  { vendor_id: 2193, fuel_type: 'Natural Gas' },
  { vendor_id: 2193, fuel_type: 'Electricity' },
  { vendor_id: 2196, fuel_type: 'Wood' },
  { vendor_id: 2197, fuel_type: 'Oil' },
  { vendor_id: 2198, fuel_type: 'Electricity' },
  { vendor_id: 2200, fuel_type: 'Electricity' },
  { vendor_id: 2200, fuel_type: 'Muni.Steam' },
  { vendor_id: 2201, fuel_type: 'Propane / LP' },
  { vendor_id: 2202, fuel_type: 'Oil' },
  { vendor_id: 2203, fuel_type: 'Propane / LP' },
  { vendor_id: 2204, fuel_type: 'Electricity' },
  { vendor_id: 2207, fuel_type: 'Oil' },
  { vendor_id: 2208, fuel_type: 'Wood' },
  { vendor_id: 2213, fuel_type: 'Propane / LP' },
  { vendor_id: 2214, fuel_type: 'Electricity' },
  { vendor_id: 2216, fuel_type: 'Oil' },
  { vendor_id: 2217, fuel_type: 'Natural Gas' },
  { vendor_id: 2217, fuel_type: 'Electricity' },
  { vendor_id: 2218, fuel_type: 'Oil' },
  { vendor_id: 2219, fuel_type: 'Oil' },
  { vendor_id: 2221, fuel_type: 'Propane / LP' },
  { vendor_id: 2223, fuel_type: 'Natural Gas' },
  { vendor_id: 2224, fuel_type: 'Electricity' },
  { vendor_id: 2225, fuel_type: 'Propane / LP' },
  { vendor_id: 2225, fuel_type: 'Oil' },
  { vendor_id: 2226, fuel_type: 'Oil' },
  { vendor_id: 2227, fuel_type: 'Oil' },
  { vendor_id: 2228, fuel_type: 'Propane / LP' },
  { vendor_id: 2230, fuel_type: 'Oil' },
  { vendor_id: 2230, fuel_type: 'Propane / LP' },
  { vendor_id: 2232, fuel_type: 'Propane / LP' },
  { vendor_id: 2232, fuel_type: 'Oil' },
  { vendor_id: 2233, fuel_type: 'Propane / LP' },
  { vendor_id: 2233, fuel_type: 'Oil' },
  { vendor_id: 2236, fuel_type: 'Oil' },
  { vendor_id: 2236, fuel_type: 'Propane / LP' },
  { vendor_id: 2238, fuel_type: 'Electricity' },
  { vendor_id: 2240, fuel_type: 'Propane / LP' },
  { vendor_id: 2243, fuel_type: 'Electricity' },
  { vendor_id: 2245, fuel_type: 'Wood' },
  { vendor_id: 2246, fuel_type: 'Electricity' },
  { vendor_id: 2247, fuel_type: 'Oil' },
  { vendor_id: 2250, fuel_type: 'Electricity' },
  { vendor_id: 2251, fuel_type: 'Electricity' },
  { vendor_id: 2252, fuel_type: 'Electricity' },
  { vendor_id: 2253, fuel_type: 'Natural Gas' },
  { vendor_id: 2253, fuel_type: 'Electricity' },
  { vendor_id: 2255, fuel_type: 'Oil' },
  { vendor_id: 2255, fuel_type: 'Propane / LP' },
  { vendor_id: 2256, fuel_type: 'Propane / LP' },
  { vendor_id: 2256, fuel_type: 'Oil' },
  { vendor_id: 2257, fuel_type: 'Propane / LP' },
  { vendor_id: 2257, fuel_type: 'Oil' },
  { vendor_id: 2258, fuel_type: 'Electricity' },
  { vendor_id: 2260, fuel_type: 'Wood' },
  { vendor_id: 2261, fuel_type: 'Oil' },
  { vendor_id: 2262, fuel_type: 'Wood' },
  { vendor_id: 2265, fuel_type: 'Wood' },
  { vendor_id: 2269, fuel_type: 'Natural Gas' },
  { vendor_id: 2271, fuel_type: 'Oil' },
  { vendor_id: 2274, fuel_type: 'Electricity' },
  { vendor_id: 2275, fuel_type: 'Wood' },
  { vendor_id: 2278, fuel_type: 'Propane / LP' },
  { vendor_id: 2279, fuel_type: 'Propane / LP' },
  { vendor_id: 2280, fuel_type: 'Electricity' },
  { vendor_id: 2281, fuel_type: 'Electricity' },
  { vendor_id: 2282, fuel_type: 'Oil' },
  { vendor_id: 2283, fuel_type: 'Muni.Steam' },
  { vendor_id: 2283, fuel_type: 'Natural Gas' },
  { vendor_id: 2283, fuel_type: 'Electricity' },
  { vendor_id: 2284, fuel_type: 'Oil' },
  { vendor_id: 2286, fuel_type: 'Oil' },
  { vendor_id: 2287, fuel_type: 'Propane / LP' },
  { vendor_id: 2288, fuel_type: 'Oil' },
  { vendor_id: 2290, fuel_type: 'Oil' },
  { vendor_id: 2291, fuel_type: 'Oil' },
  { vendor_id: 2292, fuel_type: 'Oil' },
  { vendor_id: 2293, fuel_type: 'Oil' },
  { vendor_id: 2294, fuel_type: 'Propane / LP' },
  { vendor_id: 2296, fuel_type: 'Electricity' },
  { vendor_id: 2298, fuel_type: 'Electricity' },
  { vendor_id: 2299, fuel_type: 'Propane / LP' },
  { vendor_id: 2299, fuel_type: 'Oil' },
  { vendor_id: 2300, fuel_type: 'Propane / LP' },
  { vendor_id: 2311, fuel_type: 'Propane / LP' },
  { vendor_id: 2312, fuel_type: 'Biofuel' },
  { vendor_id: 2313, fuel_type: 'Oil' },
  { vendor_id: 2325, fuel_type: 'Propane / LP' },
  { vendor_id: 2336, fuel_type: 'Propane / LP' },
  { vendor_id: 2338, fuel_type: 'Wood' },
  { vendor_id: 2340, fuel_type: 'Wood' },
  { vendor_id: 2341, fuel_type: 'Wood' },
  { vendor_id: 2346, fuel_type: 'Wood' },
  { vendor_id: 2352, fuel_type: 'Wood' },
  { vendor_id: 2358, fuel_type: 'Wood' },
  { vendor_id: 2362, fuel_type: 'Propane / LP' },
  { vendor_id: 2363, fuel_type: 'Propane / LP' },
  { vendor_id: 2363, fuel_type: 'Oil' },
  { vendor_id: 2365, fuel_type: 'Oil' },
  { vendor_id: 2367, fuel_type: 'Electricity' },
  { vendor_id: 2368, fuel_type: 'Electricity' },
  { vendor_id: 2370, fuel_type: 'Propane / LP' },
  { vendor_id: 2371, fuel_type: 'Electricity' },
  { vendor_id: 2372, fuel_type: 'Propane / LP' },
  { vendor_id: 2374, fuel_type: 'Wood' },
  { vendor_id: 2375, fuel_type: 'Wood' },
  { vendor_id: 2379, fuel_type: 'Wood' },
  { vendor_id: 2382, fuel_type: 'Wood' },
  { vendor_id: 2383, fuel_type: 'Wood' },
  { vendor_id: 2388, fuel_type: 'Wood' },
  { vendor_id: 2389, fuel_type: 'Wood' },
  { vendor_id: 2392, fuel_type: 'Oil' },
  { vendor_id: 2394, fuel_type: 'Electricity' },
  { vendor_id: 2398, fuel_type: 'Wood' },
  { vendor_id: 2399, fuel_type: 'Wood' },
  { vendor_id: 2401, fuel_type: 'Wood' },
  { vendor_id: 2405, fuel_type: 'Wood' },
  { vendor_id: 2411, fuel_type: 'Wood' },
  { vendor_id: 2412, fuel_type: 'Wood' },
  { vendor_id: 2413, fuel_type: 'Wood' },
  { vendor_id: 2415, fuel_type: 'Wood' },
  { vendor_id: 2418, fuel_type: 'Wood' },
  { vendor_id: 2420, fuel_type: 'Wood' },
  { vendor_id: 2422, fuel_type: 'Propane / LP' },
  { vendor_id: 2423, fuel_type: 'Propane / LP' },
  { vendor_id: 2423, fuel_type: 'Oil' },
  { vendor_id: 2424, fuel_type: 'Propane / LP' },
  { vendor_id: 2425, fuel_type: 'Oil' },
  { vendor_id: 2427, fuel_type: 'Oil' },
  { vendor_id: 2428, fuel_type: 'Propane / LP' },
  { vendor_id: 2430, fuel_type: 'Propane / LP' },
  { vendor_id: 2431, fuel_type: 'Oil' },
  { vendor_id: 2432, fuel_type: 'Propane / LP' },
  { vendor_id: 2432, fuel_type: 'Oil' },
  { vendor_id: 2433, fuel_type: 'Oil' },
  { vendor_id: 2434, fuel_type: 'Propane / LP' },
  { vendor_id: 2434, fuel_type: 'Oil' },
  { vendor_id: 2437, fuel_type: 'Wood' },
  { vendor_id: 2438, fuel_type: 'Propane / LP' },
  { vendor_id: 2439, fuel_type: 'Electricity' },
  { vendor_id: 2441, fuel_type: 'Propane / LP' },
  { vendor_id: 2443, fuel_type: 'Oil' },
  { vendor_id: 2447, fuel_type: 'Propane / LP' },
  { vendor_id: 2447, fuel_type: 'Oil' },
  { vendor_id: 2448, fuel_type: 'Propane / LP' },
  { vendor_id: 2449, fuel_type: 'Oil' },
  { vendor_id: 2449, fuel_type: 'Propane / LP' },
  { vendor_id: 2454, fuel_type: 'Oil' },
  { vendor_id: 2458, fuel_type: 'Wood' },
  { vendor_id: 2459, fuel_type: 'Wood' },
  { vendor_id: 2460, fuel_type: 'Wood' },
  { vendor_id: 2461, fuel_type: 'Wood' },
  { vendor_id: 2462, fuel_type: 'Wood' },
  { vendor_id: 2463, fuel_type: 'Propane / LP' },
  { vendor_id: 2466, fuel_type: 'Wood' },
  { vendor_id: 2468, fuel_type: 'Wood' },
  { vendor_id: 2469, fuel_type: 'Wood' },
  { vendor_id: 2471, fuel_type: 'Wood' },
  { vendor_id: 2472, fuel_type: 'Wood' },
  { vendor_id: 2473, fuel_type: 'Wood' },
  { vendor_id: 2474, fuel_type: 'Wood' },
  { vendor_id: 2475, fuel_type: 'Wood' },
  { vendor_id: 2476, fuel_type: 'Wood' },
  { vendor_id: 2477, fuel_type: 'Wood' },
  { vendor_id: 2478, fuel_type: 'Wood' },
  { vendor_id: 2479, fuel_type: 'Wood' },
  { vendor_id: 2480, fuel_type: 'Wood' },
  { vendor_id: 2481, fuel_type: 'Propane / LP' },
  { vendor_id: 2497, fuel_type: 'Wood' },
  { vendor_id: 2505, fuel_type: 'Wood' },
  { vendor_id: 2516, fuel_type: 'Propane / LP' },
  { vendor_id: 2516, fuel_type: 'Oil' },
  { vendor_id: 2518, fuel_type: 'Propane / LP' },
  { vendor_id: 2519, fuel_type: 'Propane / LP' },
  { vendor_id: 2520, fuel_type: 'Oil' },
  { vendor_id: 2520, fuel_type: 'Propane / LP' },
  { vendor_id: 2521, fuel_type: 'Electricity' },
  { vendor_id: 2522, fuel_type: 'Oil' },
  { vendor_id: 2523, fuel_type: 'Propane / LP' },
  { vendor_id: 2527, fuel_type: 'Propane / LP' },
  { vendor_id: 2528, fuel_type: 'Propane / LP' },
  { vendor_id: 2529, fuel_type: 'Oil' },
  { vendor_id: 2530, fuel_type: 'Oil' },
  { vendor_id: 2531, fuel_type: 'Oil' },
  { vendor_id: 2532, fuel_type: 'Propane / LP' },
  { vendor_id: 2533, fuel_type: 'Propane / LP' },
  { vendor_id: 2535, fuel_type: 'Propane / LP' },
  { vendor_id: 2536, fuel_type: 'Wood' },
  { vendor_id: 2537, fuel_type: 'Wood' },
  { vendor_id: 2538, fuel_type: 'Wood' },
  { vendor_id: 2539, fuel_type: 'Wood' },
  { vendor_id: 2539, fuel_type: 'Biofuel' },
  { vendor_id: 2541, fuel_type: 'Oil' },
  { vendor_id: 2541, fuel_type: 'Propane / LP' },
  { vendor_id: 2542, fuel_type: 'Wood' },
  { vendor_id: 2543, fuel_type: 'Wood' },
  { vendor_id: 2544, fuel_type: 'Wood' },
  { vendor_id: 2545, fuel_type: 'Propane / LP' },
  { vendor_id: 2546, fuel_type: 'Electricity' },
  { vendor_id: 2547, fuel_type: 'Propane / LP' },
  { vendor_id: 2549, fuel_type: 'Wood' },
  { vendor_id: 2550, fuel_type: 'Wood' },
  { vendor_id: 2551, fuel_type: 'Wood' },
  { vendor_id: 2552, fuel_type: 'Wood' },
  { vendor_id: 2553, fuel_type: 'Wood' },
  { vendor_id: 2554, fuel_type: 'Oil' },
  { vendor_id: 2555, fuel_type: 'Oil' },
  { vendor_id: 2556, fuel_type: 'Oil' },
  { vendor_id: 2557, fuel_type: 'Wood' },
  { vendor_id: 2558, fuel_type: 'Wood' },
  { vendor_id: 2559, fuel_type: 'Wood' },
  { vendor_id: 2560, fuel_type: 'Propane / LP' },
  { vendor_id: 2561, fuel_type: 'Wood' },
  { vendor_id: 2562, fuel_type: 'Propane / LP' },
  { vendor_id: 2563, fuel_type: 'Biofuel' },
  { vendor_id: 2564, fuel_type: 'Wood' },
  { vendor_id: 2565, fuel_type: 'Wood' },
  { vendor_id: 2566, fuel_type: 'Wood' },
  { vendor_id: 2567, fuel_type: 'Wood' },
  { vendor_id: 2568, fuel_type: 'Wood' },
  { vendor_id: 2569, fuel_type: 'Oil' },
  { vendor_id: 2570, fuel_type: 'Wood' },
  { vendor_id: 2571, fuel_type: 'Wood' },
  { vendor_id: 2572, fuel_type: 'Propane / LP' },
  { vendor_id: 2573, fuel_type: 'Wood' },
  { vendor_id: 2574, fuel_type: 'Wood' },
  { vendor_id: 2575, fuel_type: 'Wood' },
  { vendor_id: 2576, fuel_type: 'Wood' },
  { vendor_id: 2577, fuel_type: 'Wood' },
  { vendor_id: 2578, fuel_type: 'Wood' },
  { vendor_id: 2579, fuel_type: 'Wood' },
  { vendor_id: 2580, fuel_type: 'Wood' },
  { vendor_id: 2581, fuel_type: 'Propane / LP' },
  { vendor_id: 2582, fuel_type: 'Propane / LP' },
  { vendor_id: 2583, fuel_type: 'Wood' },
  { vendor_id: 2584, fuel_type: 'Wood' },
  { vendor_id: 2585, fuel_type: 'Wood' },
  { vendor_id: 2586, fuel_type: 'Wood' },
  { vendor_id: 2587, fuel_type: 'Wood' },
  { vendor_id: 2588, fuel_type: 'Wood' },
  { vendor_id: 2589, fuel_type: 'Wood' },
  { vendor_id: 2590, fuel_type: 'Wood' },
  { vendor_id: 2591, fuel_type: 'Wood' },
  { vendor_id: 2592, fuel_type: 'Wood' },
  { vendor_id: 2593, fuel_type: 'Propane / LP' },
  { vendor_id: 2594, fuel_type: 'Oil' },
  { vendor_id: 2595, fuel_type: 'Wood' },
  { vendor_id: 2596, fuel_type: 'Wood' },
  { vendor_id: 2597, fuel_type: 'Electricity' },
  { vendor_id: 2598, fuel_type: 'Wood' },
  { vendor_id: 2599, fuel_type: 'Wood' },
  { vendor_id: 2600, fuel_type: 'Wood' },
  { vendor_id: 2601, fuel_type: 'Wood' },
  { vendor_id: 2602, fuel_type: 'Wood' },
  { vendor_id: 2603, fuel_type: 'Wood' },
  { vendor_id: 2605, fuel_type: 'Wood' },
  { vendor_id: 2606, fuel_type: 'Wood' },
  { vendor_id: 2607, fuel_type: 'Wood' },
  { vendor_id: 2608, fuel_type: 'Wood' },
  { vendor_id: 2609, fuel_type: 'Wood' },
  { vendor_id: 2610, fuel_type: 'Wood' },
  { vendor_id: 2611, fuel_type: 'Wood' },
  { vendor_id: 2612, fuel_type: 'Propane / LP' },
  { vendor_id: 2612, fuel_type: 'Oil' },
  { vendor_id: 2613, fuel_type: 'Wood' },
  { vendor_id: 2614, fuel_type: 'Wood' },
  { vendor_id: 2615, fuel_type: 'Wood' },
  { vendor_id: 2616, fuel_type: 'Wood' },
  { vendor_id: 2617, fuel_type: 'Wood' },
  { vendor_id: 2618, fuel_type: 'Wood' },
  { vendor_id: 2619, fuel_type: 'Wood' },
  { vendor_id: 2620, fuel_type: 'Wood' },
  { vendor_id: 2621, fuel_type: 'Wood' },
  { vendor_id: 2622, fuel_type: 'Wood' },
  { vendor_id: 2623, fuel_type: 'Wood' },
  { vendor_id: 2624, fuel_type: 'Wood' },
  { vendor_id: 2625, fuel_type: 'Wood' },
  { vendor_id: 2626, fuel_type: 'Wood' },
  { vendor_id: 2627, fuel_type: 'Wood' },
  { vendor_id: 2628, fuel_type: 'Wood' },
  { vendor_id: 2629, fuel_type: 'Wood' },
  { vendor_id: 2630, fuel_type: 'Electricity' },
  { vendor_id: 2631, fuel_type: 'Wood' },
  { vendor_id: 2632, fuel_type: 'Wood' },
  { vendor_id: 2633, fuel_type: 'Wood' },
  { vendor_id: 2634, fuel_type: 'Wood' },
  { vendor_id: 2635, fuel_type: 'Propane / LP' },
  { vendor_id: 2636, fuel_type: 'Wood' },
  { vendor_id: 2637, fuel_type: 'Wood' },
  { vendor_id: 2638, fuel_type: 'Oil' },
  { vendor_id: 2639, fuel_type: 'Electricity' },
  { vendor_id: 2640, fuel_type: 'Wood' },
  { vendor_id: 2641, fuel_type: 'Oil' },
  { vendor_id: 2642, fuel_type: 'Wood' },
  { vendor_id: 2643, fuel_type: 'Wood' },
  { vendor_id: 2644, fuel_type: 'Wood' },
  { vendor_id: 2645, fuel_type: 'Wood' },
  { vendor_id: 2646, fuel_type: 'Electricity' },
  { vendor_id: 2647, fuel_type: 'Wood' },
  { vendor_id: 2648, fuel_type: 'Wood' },
  { vendor_id: 2649, fuel_type: 'Propane / LP' },
  { vendor_id: 2649, fuel_type: 'Wood' },
  { vendor_id: 2650, fuel_type: 'Wood' },
  { vendor_id: 2651, fuel_type: 'Propane / LP' },
  { vendor_id: 2652, fuel_type: 'Wood' },
  { vendor_id: 2653, fuel_type: 'Wood' },
  { vendor_id: 2654, fuel_type: 'Propane / LP' },
  { vendor_id: 2655, fuel_type: 'Wood' },
  { vendor_id: 2656, fuel_type: 'Propane / LP' },
  { vendor_id: 2657, fuel_type: 'Wood' },
  { vendor_id: 2658, fuel_type: 'Wood' },
  { vendor_id: 2659, fuel_type: 'Wood' },
  { vendor_id: 2660, fuel_type: 'Propane / LP' },
  { vendor_id: 2661, fuel_type: 'Wood' },
  { vendor_id: 2662, fuel_type: 'Wood' },
  { vendor_id: 2663, fuel_type: 'Wood' },
  { vendor_id: 2664, fuel_type: 'Wood' },
  { vendor_id: 2665, fuel_type: 'Wood' },
  { vendor_id: 2666, fuel_type: 'Wood' },
  { vendor_id: 2667, fuel_type: 'Wood' },
  { vendor_id: 2668, fuel_type: 'Wood' },
  { vendor_id: 2669, fuel_type: 'Wood' },
  { vendor_id: 2670, fuel_type: 'Wood' },
  { vendor_id: 2671, fuel_type: 'Wood' },
  { vendor_id: 2672, fuel_type: 'Wood' },
  { vendor_id: 2673, fuel_type: 'Propane / LP' },
  { vendor_id: 2674, fuel_type: 'Wood' },
  { vendor_id: 2675, fuel_type: 'Wood' },
  { vendor_id: 2676, fuel_type: 'Wood' },
  { vendor_id: 2677, fuel_type: 'Wood' },
  { vendor_id: 2678, fuel_type: 'Wood' },
  { vendor_id: 2679, fuel_type: 'Wood' },
  { vendor_id: 2680, fuel_type: 'Wood' },
  { vendor_id: 2681, fuel_type: 'Wood' },
  { vendor_id: 2682, fuel_type: 'Wood' },
  { vendor_id: 2683, fuel_type: 'Wood' },
  { vendor_id: 2684, fuel_type: 'Propane / LP' },
  { vendor_id: 2685, fuel_type: 'Wood' },
  { vendor_id: 2686, fuel_type: 'Oil' },
  { vendor_id: 2687, fuel_type: 'Wood' },
  { vendor_id: 2688, fuel_type: 'Wood' },
  { vendor_id: 2689, fuel_type: 'Propane / LP' },
  { vendor_id: 2690, fuel_type: 'Wood' },
  { vendor_id: 2691, fuel_type: 'Wood' },
  { vendor_id: 2692, fuel_type: 'Wood' },
  { vendor_id: 2694, fuel_type: 'Wood' },
  { vendor_id: 2695, fuel_type: 'Wood' },
  { vendor_id: 2696, fuel_type: 'Wood' },
  { vendor_id: 2697, fuel_type: 'Wood' },
  { vendor_id: 2698, fuel_type: 'Wood' },
  { vendor_id: 2699, fuel_type: 'Wood' },
  { vendor_id: 2700, fuel_type: 'Propane / LP' },
  { vendor_id: 2701, fuel_type: 'Wood' },
  { vendor_id: 2702, fuel_type: 'Propane / LP' },
  { vendor_id: 2703, fuel_type: 'Wood' },
  { vendor_id: 2704, fuel_type: 'Wood' },
  { vendor_id: 2705, fuel_type: 'Propane / LP' },
  { vendor_id: 2706, fuel_type: 'Propane / LP' },
  { vendor_id: 2706, fuel_type: 'Oil' },
  { vendor_id: 2707, fuel_type: 'Wood' },
  { vendor_id: 2708, fuel_type: 'Wood' },
  { vendor_id: 2709, fuel_type: 'Wood' },
  { vendor_id: 2710, fuel_type: 'Wood' },
  { vendor_id: 2711, fuel_type: 'Wood' },
  { vendor_id: 2712, fuel_type: 'Propane / LP' },
  { vendor_id: 2713, fuel_type: 'Wood' },
  { vendor_id: 2714, fuel_type: 'Natural Gas' },
  { vendor_id: 2714, fuel_type: 'Propane / LP' },
  { vendor_id: 2715, fuel_type: 'Wood' },
  { vendor_id: 2716, fuel_type: 'Wood' },
  { vendor_id: 2717, fuel_type: 'Wood' },
  { vendor_id: 2718, fuel_type: 'Wood' },
  { vendor_id: 2719, fuel_type: 'Wood' },
  { vendor_id: 2720, fuel_type: 'Propane / LP' },
  { vendor_id: 2721, fuel_type: 'Wood' },
  { vendor_id: 2722, fuel_type: 'Wood' },
  { vendor_id: 2723, fuel_type: 'Wood' },
  { vendor_id: 2724, fuel_type: 'Wood' },
  { vendor_id: 2725, fuel_type: 'Wood' },
  { vendor_id: 2726, fuel_type: 'Propane / LP' },
  { vendor_id: 2727, fuel_type: 'Propane / LP' },
  { vendor_id: 2728, fuel_type: 'Electricity' },
  { vendor_id: 2729, fuel_type: 'Wood' },
  { vendor_id: 2730, fuel_type: 'Wood' },
  { vendor_id: 2731, fuel_type: 'Wood' },
  { vendor_id: 2732, fuel_type: 'Propane / LP' },
  { vendor_id: 2734, fuel_type: 'Wood' },
  { vendor_id: 2735, fuel_type: 'Propane / LP' },
  { vendor_id: 2736, fuel_type: 'Wood' },
  { vendor_id: 2737, fuel_type: 'Wood' },
  { vendor_id: 2738, fuel_type: 'Biofuel' },
  { vendor_id: 2739, fuel_type: 'Wood' },
  { vendor_id: 2740, fuel_type: 'Wood' },
  { vendor_id: 2741, fuel_type: 'Propane / LP' },
  { vendor_id: 2742, fuel_type: 'Wood' },
  { vendor_id: 2743, fuel_type: 'Propane / LP' },
  { vendor_id: 2744, fuel_type: 'Wood' },
  { vendor_id: 2745, fuel_type: 'Wood' },
  { vendor_id: 2746, fuel_type: 'Wood' },
  { vendor_id: 2747, fuel_type: 'Wood' },
  { vendor_id: 2748, fuel_type: 'Wood' },
  { vendor_id: 2749, fuel_type: 'Wood' },
  { vendor_id: 2750, fuel_type: 'Wood' },
  { vendor_id: 2751, fuel_type: 'Wood' },
  { vendor_id: 2752, fuel_type: 'Wood' },
  { vendor_id: 2753, fuel_type: 'Oil' },
  { vendor_id: 2754, fuel_type: 'Wood' },
  { vendor_id: 2756, fuel_type: 'Electricity' },
  { vendor_id: 2757, fuel_type: 'Wood' },
  { vendor_id: 2758, fuel_type: 'Wood' },
  { vendor_id: 2759, fuel_type: 'Wood' },
  { vendor_id: 2760, fuel_type: 'Wood' },
  { vendor_id: 2762, fuel_type: 'Wood' },
  { vendor_id: 2763, fuel_type: 'Propane / LP' },
  { vendor_id: 2763, fuel_type: 'Oil' },
  { vendor_id: 2764, fuel_type: 'Muni.Steam' },
  { vendor_id: 2765, fuel_type: 'Wood' },
  { vendor_id: 2766, fuel_type: 'Wood' },
  { vendor_id: 2767, fuel_type: 'Wood' },
  { vendor_id: 2768, fuel_type: 'Wood' },
  { vendor_id: 2769, fuel_type: 'Wood' },
  { vendor_id: 2770, fuel_type: 'Propane / LP' },
  { vendor_id: 2771, fuel_type: 'Propane / LP' },
  { vendor_id: 2772, fuel_type: 'Wood' },
  { vendor_id: 2773, fuel_type: 'Wood' },
  { vendor_id: 2774, fuel_type: 'Propane / LP' },
  { vendor_id: 2775, fuel_type: 'Wood' },
  { vendor_id: 2776, fuel_type: 'Wood' },
  { vendor_id: 2777, fuel_type: 'Wood' },
  { vendor_id: 2778, fuel_type: 'Propane / LP' },
  { vendor_id: 2779, fuel_type: 'Wood' },
  { vendor_id: 2780, fuel_type: 'Wood' },
  { vendor_id: 2781, fuel_type: 'Propane / LP' },
  { vendor_id: 2782, fuel_type: 'Wood' },
  { vendor_id: 2783, fuel_type: 'Wood' },
  { vendor_id: 2784, fuel_type: 'Wood' },
  { vendor_id: 2785, fuel_type: 'Wood' },
  { vendor_id: 2788, fuel_type: 'Wood' },
  { vendor_id: 2789, fuel_type: 'Wood' },
  { vendor_id: 2790, fuel_type: 'Propane / LP' },
  { vendor_id: 2791, fuel_type: 'Wood' },
  { vendor_id: 2792, fuel_type: 'Oil' },
  { vendor_id: 2793, fuel_type: 'Wood' },
  { vendor_id: 2795, fuel_type: 'Wood' },
  { vendor_id: 2796, fuel_type: 'Wood' },
  { vendor_id: 2797, fuel_type: 'Wood' },
  { vendor_id: 2798, fuel_type: 'Wood' },
  { vendor_id: 2799, fuel_type: 'Wood' },
  { vendor_id: 2800, fuel_type: 'Oil' },
  { vendor_id: 2801, fuel_type: 'Wood' },
  { vendor_id: 2802, fuel_type: 'Propane / LP' },
  { vendor_id: 2803, fuel_type: 'Propane / LP' },
  { vendor_id: 2804, fuel_type: 'Natural Gas' },
  { vendor_id: 2805, fuel_type: 'Natural Gas' },
  { vendor_id: 2806, fuel_type: 'Propane / LP' },
  { vendor_id: 2806, fuel_type: 'Oil' },
  { vendor_id: 2807, fuel_type: 'Propane / LP' },
  { vendor_id: 2808, fuel_type: 'Wood' },
  { vendor_id: 2809, fuel_type: 'Propane / LP' },
  { vendor_id: 2810, fuel_type: 'Wood' },
  { vendor_id: 2812, fuel_type: 'Wood' },
  { vendor_id: 2813, fuel_type: 'Wood' },
  { vendor_id: 2814, fuel_type: 'Wood' },
  { vendor_id: 2815, fuel_type: 'Wood' },
  { vendor_id: 2816, fuel_type: 'Wood' },
  { vendor_id: 2817, fuel_type: 'Wood' },
  { vendor_id: 2818, fuel_type: 'Wood' },
  { vendor_id: 2819, fuel_type: 'Wood' },
  { vendor_id: 2820, fuel_type: 'Wood' },
  { vendor_id: 2821, fuel_type: 'Wood' },
  { vendor_id: 2822, fuel_type: 'Wood' },
  { vendor_id: 2823, fuel_type: 'Wood' },
  { vendor_id: 2824, fuel_type: 'Wood' },
  { vendor_id: 2825, fuel_type: 'Propane / LP' },
  { vendor_id: 2826, fuel_type: 'Wood' },
  { vendor_id: 2827, fuel_type: 'Wood' },
  { vendor_id: 2828, fuel_type: 'Wood' },
  { vendor_id: 2829, fuel_type: 'Wood' },
  { vendor_id: 2830, fuel_type: 'Wood' },
  { vendor_id: 2831, fuel_type: 'Wood' },
  { vendor_id: 2832, fuel_type: 'Wood' },
  { vendor_id: 2833, fuel_type: 'Wood' },
  { vendor_id: 2834, fuel_type: 'Oil' },
  { vendor_id: 2835, fuel_type: 'Wood' },
  { vendor_id: 2836, fuel_type: 'Wood' },
  { vendor_id: 2837, fuel_type: 'Wood' },
  { vendor_id: 2838, fuel_type: 'Oil' },
  { vendor_id: 2839, fuel_type: 'Wood' },
  { vendor_id: 2840, fuel_type: 'Propane / LP' },
  { vendor_id: 2841, fuel_type: 'Propane / LP' },
  { vendor_id: 2842, fuel_type: 'Propane / LP' },
  { vendor_id: 2843, fuel_type: 'Wood' },
  { vendor_id: 2844, fuel_type: 'Wood' },
  { vendor_id: 2845, fuel_type: 'Wood' },
  { vendor_id: 2846, fuel_type: 'Wood' },
  { vendor_id: 2847, fuel_type: 'Wood' },
  { vendor_id: 2848, fuel_type: 'Wood' },
  { vendor_id: 2849, fuel_type: 'Wood' },
  { vendor_id: 2850, fuel_type: 'Oil' },
  { vendor_id: 2851, fuel_type: 'Wood' },
  { vendor_id: 2852, fuel_type: 'Wood' },
  { vendor_id: 2853, fuel_type: 'Wood' },
  { vendor_id: 2854, fuel_type: 'Wood' },
  { vendor_id: 2855, fuel_type: 'Wood' },
  { vendor_id: 2856, fuel_type: 'Wood' },
  { vendor_id: 2857, fuel_type: 'Wood' },
  { vendor_id: 2858, fuel_type: 'Wood' },
  { vendor_id: 2859, fuel_type: 'Wood' },
  { vendor_id: 2860, fuel_type: 'Wood' },
  { vendor_id: 2861, fuel_type: 'Wood' },
  { vendor_id: 2863, fuel_type: 'Wood' },
  { vendor_id: 2864, fuel_type: 'Wood' },
  { vendor_id: 2865, fuel_type: 'Wood' },
  { vendor_id: 2866, fuel_type: 'Wood' },
  { vendor_id: 2867, fuel_type: 'Wood' },
  { vendor_id: 2868, fuel_type: 'Wood' },
  { vendor_id: 2869, fuel_type: 'Wood' },
  { vendor_id: 2870, fuel_type: 'Wood' },
  { vendor_id: 2872, fuel_type: 'Wood' },
  { vendor_id: 2873, fuel_type: 'Wood' },
  { vendor_id: 2874, fuel_type: 'Wood' },
  { vendor_id: 2875, fuel_type: 'Wood' },
  { vendor_id: 2876, fuel_type: 'Wood' },
  { vendor_id: 2877, fuel_type: 'Wood' },
  { vendor_id: 2878, fuel_type: 'Wood' },
  { vendor_id: 2879, fuel_type: 'Wood' },
  { vendor_id: 2881, fuel_type: 'Wood' },
  { vendor_id: 2882, fuel_type: 'Propane / LP' },
  { vendor_id: 2882, fuel_type: 'Oil' },
  { vendor_id: 2883, fuel_type: 'Propane / LP' },
  { vendor_id: 2884, fuel_type: 'Wood' },
  { vendor_id: 2885, fuel_type: 'Propane / LP' },
  { vendor_id: 2885, fuel_type: 'Oil' },
  { vendor_id: 2886, fuel_type: 'Wood' },
  { vendor_id: 2887, fuel_type: 'Propane / LP' },
  { vendor_id: 2888, fuel_type: 'Wood' },
  { vendor_id: 2889, fuel_type: 'Wood' },
  { vendor_id: 2890, fuel_type: 'Wood' },
  { vendor_id: 2891, fuel_type: 'Wood' },
  { vendor_id: 2892, fuel_type: 'Propane / LP' },
  { vendor_id: 2893, fuel_type: 'Wood' },
  { vendor_id: 2894, fuel_type: 'Wood' },
  { vendor_id: 2895, fuel_type: 'Electricity' },
  { vendor_id: 2896, fuel_type: 'Wood' },
  { vendor_id: 2897, fuel_type: 'Wood' },
  { vendor_id: 2898, fuel_type: 'Wood' },
  { vendor_id: 2899, fuel_type: 'Wood' },
  { vendor_id: 2900, fuel_type: 'Wood' },
  { vendor_id: 2901, fuel_type: 'Wood' },
  { vendor_id: 2902, fuel_type: 'Wood' },
  { vendor_id: 2903, fuel_type: 'Wood' },
  { vendor_id: 2904, fuel_type: 'Wood' },
  { vendor_id: 2905, fuel_type: 'Wood' },
  { vendor_id: 2906, fuel_type: 'Wood' },
  { vendor_id: 2907, fuel_type: 'Wood' },
  { vendor_id: 2908, fuel_type: 'Wood' },
  { vendor_id: 2909, fuel_type: 'Wood' },
  { vendor_id: 2910, fuel_type: 'Wood' },
  { vendor_id: 2911, fuel_type: 'Wood' },
  { vendor_id: 2912, fuel_type: 'Wood' },
  { vendor_id: 2913, fuel_type: 'Propane / LP' },
  { vendor_id: 2914, fuel_type: 'Electricity' },
  { vendor_id: 2915, fuel_type: 'Wood' },
  { vendor_id: 2916, fuel_type: 'Wood' },
  { vendor_id: 2917, fuel_type: 'Wood' },
  { vendor_id: 2918, fuel_type: 'Wood' },
  { vendor_id: 2919, fuel_type: 'Wood' },
  { vendor_id: 2920, fuel_type: 'Wood' },
  { vendor_id: 2921, fuel_type: 'Wood' },
  { vendor_id: 2922, fuel_type: 'Wood' },
  { vendor_id: 2923, fuel_type: 'Wood' },
  { vendor_id: 2924, fuel_type: 'Propane / LP' },
  { vendor_id: 2925, fuel_type: 'Wood' },
  { vendor_id: 2926, fuel_type: 'Wood' },
  { vendor_id: 2927, fuel_type: 'Wood' },
  { vendor_id: 2928, fuel_type: 'Propane / LP' },
  { vendor_id: 2929, fuel_type: 'Wood' },
  { vendor_id: 2930, fuel_type: 'Oil' },
  { vendor_id: 2931, fuel_type: 'Propane / LP' },
  { vendor_id: 2932, fuel_type: 'Oil' },
  { vendor_id: 2933, fuel_type: 'Propane / LP' },
  { vendor_id: 2934, fuel_type: 'Wood' },
  { vendor_id: 2935, fuel_type: 'Propane / LP' },
  { vendor_id: 2936, fuel_type: 'Propane / LP' },
  { vendor_id: 2936, fuel_type: 'Biofuel' },
  { vendor_id: 2937, fuel_type: 'Wood' },
  { vendor_id: 2938, fuel_type: 'Wood' },
  { vendor_id: 2939, fuel_type: 'Wood' },
  { vendor_id: 2940, fuel_type: 'Propane / LP' },
  { vendor_id: 2941, fuel_type: 'Electricity' },
  { vendor_id: 2942, fuel_type: 'Propane / LP' },
  { vendor_id: 2943, fuel_type: 'Wood' },
  { vendor_id: 2944, fuel_type: 'Wood' },
  { vendor_id: 2945, fuel_type: 'Wood' },
  { vendor_id: 2946, fuel_type: 'Wood' },
  { vendor_id: 2947, fuel_type: 'Wood' },
  { vendor_id: 2948, fuel_type: 'Oil' },
  { vendor_id: 2949, fuel_type: 'Propane / LP' },
  { vendor_id: 2949, fuel_type: 'Oil' },
  { vendor_id: 2950, fuel_type: 'Wood' },
  { vendor_id: 2951, fuel_type: 'Wood' },
  { vendor_id: 2952, fuel_type: 'Wood' },
  { vendor_id: 2953, fuel_type: 'Wood' },
  { vendor_id: 2954, fuel_type: 'Oil' },
  { vendor_id: 2955, fuel_type: 'Wood' },
  { vendor_id: 2956, fuel_type: 'Wood' },
  { vendor_id: 2957, fuel_type: 'Wood' },
  { vendor_id: 2958, fuel_type: 'Wood' },
  { vendor_id: 2959, fuel_type: 'Wood' },
  { vendor_id: 2960, fuel_type: 'Wood' },
  { vendor_id: 2961, fuel_type: 'Wood' },
  { vendor_id: 2962, fuel_type: 'Wood' },
  { vendor_id: 2963, fuel_type: 'Wood' },
  { vendor_id: 2964, fuel_type: 'Propane / LP' },
  { vendor_id: 2964, fuel_type: 'Metered Propane/LP' },
  { vendor_id: 2965, fuel_type: 'Wood' },
  { vendor_id: 2966, fuel_type: 'Wood' },
  { vendor_id: 2967, fuel_type: 'Wood' },
  { vendor_id: 2968, fuel_type: 'Wood' },
  { vendor_id: 2969, fuel_type: 'Wood' },
  { vendor_id: 2970, fuel_type: 'Wood' },
  { vendor_id: 2971, fuel_type: 'Wood' },
  { vendor_id: 2972, fuel_type: 'Oil' },
  { vendor_id: 2973, fuel_type: 'Wood' },
  { vendor_id: 2974, fuel_type: 'Wood' },
  { vendor_id: 2975, fuel_type: 'Wood' },
  { vendor_id: 2976, fuel_type: 'Wood' },
  { vendor_id: 2977, fuel_type: 'Wood' },
  { vendor_id: 2978, fuel_type: 'Wood' },
  { vendor_id: 2979, fuel_type: 'Wood' },
  { vendor_id: 2980, fuel_type: 'Wood' },
  { vendor_id: 2981, fuel_type: 'Wood' },
  { vendor_id: 2982, fuel_type: 'Wood' },
  { vendor_id: 2983, fuel_type: 'Wood' },
  { vendor_id: 2984, fuel_type: 'Wood' },
  { vendor_id: 2985, fuel_type: 'Wood' },
  { vendor_id: 2986, fuel_type: 'Wood' },
  { vendor_id: 2987, fuel_type: 'Wood' },
  { vendor_id: 2988, fuel_type: 'Wood' },
  { vendor_id: 2989, fuel_type: 'Wood' },
  { vendor_id: 2990, fuel_type: 'Wood' },
  { vendor_id: 2991, fuel_type: 'Wood' },
  { vendor_id: 2992, fuel_type: 'Wood' },
  { vendor_id: 2993, fuel_type: 'Wood' },
  { vendor_id: 2994, fuel_type: 'Wood' },
  { vendor_id: 2995, fuel_type: 'Wood' },
  { vendor_id: 2996, fuel_type: 'Wood' },
  { vendor_id: 2997, fuel_type: 'Wood' },
  { vendor_id: 2998, fuel_type: 'Wood' },
  { vendor_id: 2999, fuel_type: 'Wood' },
  { vendor_id: 3000, fuel_type: 'Wood' },
  { vendor_id: 3001, fuel_type: 'Wood' },
  { vendor_id: 3002, fuel_type: 'Wood' },
  { vendor_id: 3003, fuel_type: 'Wood' },
  { vendor_id: 3004, fuel_type: 'Wood' },
  { vendor_id: 3005, fuel_type: 'Wood' },
  { vendor_id: 3006, fuel_type: 'Wood' },
  { vendor_id: 3007, fuel_type: 'Wood' },
  { vendor_id: 3008, fuel_type: 'Wood' },
  { vendor_id: 3009, fuel_type: 'Wood' },
  { vendor_id: 3010, fuel_type: 'Wood' },
  { vendor_id: 3011, fuel_type: 'Wood' },
  { vendor_id: 3012, fuel_type: 'Wood' },
  { vendor_id: 3013, fuel_type: 'Wood' },
  { vendor_id: 3014, fuel_type: 'Propane / LP' },
  { vendor_id: 3015, fuel_type: 'Wood' },
  { vendor_id: 3016, fuel_type: 'Wood' },
  { vendor_id: 3017, fuel_type: 'Propane / LP' },
  { vendor_id: 3018, fuel_type: 'Wood' },
  { vendor_id: 3019, fuel_type: 'Wood' },
  { vendor_id: 3020, fuel_type: 'Wood' },
  { vendor_id: 3021, fuel_type: 'Wood' },
  { vendor_id: 3022, fuel_type: 'Wood' },
  { vendor_id: 3023, fuel_type: 'Wood' },
  { vendor_id: 3024, fuel_type: 'Wood' },
  { vendor_id: 3025, fuel_type: 'Wood' },
  { vendor_id: 3026, fuel_type: 'Wood' },
  { vendor_id: 3027, fuel_type: 'Wood' },
  { vendor_id: 3028, fuel_type: 'Wood' },
  { vendor_id: 3029, fuel_type: 'Wood' },
  { vendor_id: 3030, fuel_type: 'Wood' },
  { vendor_id: 3031, fuel_type: 'Wood' },
  { vendor_id: 3032, fuel_type: 'Wood' },
  { vendor_id: 3033, fuel_type: 'Propane / LP' },
  { vendor_id: 3034, fuel_type: 'Wood' },
  { vendor_id: 3035, fuel_type: 'Wood' },
  { vendor_id: 3036, fuel_type: 'Wood' },
  { vendor_id: 3037, fuel_type: 'Wood' },
  { vendor_id: 3038, fuel_type: 'Wood' },
  { vendor_id: 3039, fuel_type: 'Wood' },
  { vendor_id: 3040, fuel_type: 'Wood' },
  { vendor_id: 3041, fuel_type: 'Wood' },
  { vendor_id: 3043, fuel_type: 'Wood' },
  { vendor_id: 3044, fuel_type: 'Wood' },
  { vendor_id: 3045, fuel_type: 'Propane / LP' },
  { vendor_id: 3046, fuel_type: 'Wood' },
  { vendor_id: 3047, fuel_type: 'Wood' },
  { vendor_id: 3048, fuel_type: 'Propane / LP' },
  { vendor_id: 3049, fuel_type: 'Wood' },
  { vendor_id: 3050, fuel_type: 'Wood' },
  { vendor_id: 3051, fuel_type: 'Wood' },
  { vendor_id: 3052, fuel_type: 'Wood' },
  { vendor_id: 3053, fuel_type: 'Wood' },
  { vendor_id: 3054, fuel_type: 'Wood' },
  { vendor_id: 3055, fuel_type: 'Wood' },
  { vendor_id: 3056, fuel_type: 'Wood' },
  { vendor_id: 3057, fuel_type: 'Wood' },
  { vendor_id: 3058, fuel_type: 'Wood' },
  { vendor_id: 3059, fuel_type: 'Biofuel' },
  { vendor_id: 3060, fuel_type: 'Wood' },
  { vendor_id: 3061, fuel_type: 'Wood' },
  { vendor_id: 3062, fuel_type: 'Wood' },
  { vendor_id: 3063, fuel_type: 'Wood' },
  { vendor_id: 3064, fuel_type: 'Wood' },
  { vendor_id: 3065, fuel_type: 'Wood' },
  { vendor_id: 3066, fuel_type: 'Wood' },
  { vendor_id: 3067, fuel_type: 'Wood' },
  { vendor_id: 3068, fuel_type: 'Wood' },
  { vendor_id: 3069, fuel_type: 'Wood' },
  { vendor_id: 3070, fuel_type: 'Wood' },
  { vendor_id: 3071, fuel_type: 'Propane / LP' },
  { vendor_id: 3072, fuel_type: 'Wood' },
  { vendor_id: 3073, fuel_type: 'Wood' },
  { vendor_id: 3074, fuel_type: 'Wood' },
  { vendor_id: 3075, fuel_type: 'Wood' },
  { vendor_id: 3076, fuel_type: 'Wood' },
  { vendor_id: 3077, fuel_type: 'Wood' },
  { vendor_id: 3078, fuel_type: 'Wood' },
  { vendor_id: 3079, fuel_type: 'Wood' },
  { vendor_id: 3080, fuel_type: 'Wood' },
  { vendor_id: 3081, fuel_type: 'Biofuel' },
  { vendor_id: 3083, fuel_type: 'Wood' },
  { vendor_id: 3084, fuel_type: 'Wood' },
  { vendor_id: 3085, fuel_type: 'Wood' },
  { vendor_id: 3086, fuel_type: 'Electricity' },
  { vendor_id: 3087, fuel_type: 'Propane / LP' },
  { vendor_id: 3088, fuel_type: 'Electricity' },
  { vendor_id: 3089, fuel_type: 'Wood' },
  { vendor_id: 3090, fuel_type: 'Wood' },
  { vendor_id: 3091, fuel_type: 'Wood' },
  { vendor_id: 3092, fuel_type: 'Wood' },
  { vendor_id: 3093, fuel_type: 'Wood' },
  { vendor_id: 3094, fuel_type: 'Wood' },
  { vendor_id: 3095, fuel_type: 'Wood' },
  { vendor_id: 3096, fuel_type: 'Wood' },
  { vendor_id: 3097, fuel_type: 'Propane / LP' },
  { vendor_id: 3098, fuel_type: 'Propane / LP' },
  { vendor_id: 3099, fuel_type: 'Wood' },
  { vendor_id: 3100, fuel_type: 'Wood' },
  { vendor_id: 3101, fuel_type: 'Wood' },
  { vendor_id: 3102, fuel_type: 'Wood' },
  { vendor_id: 3104, fuel_type: 'Wood' },
  { vendor_id: 3105, fuel_type: 'Wood' },
  { vendor_id: 3106, fuel_type: 'Wood' },
  { vendor_id: 3106, fuel_type: 'Biofuel' },
  { vendor_id: 3107, fuel_type: 'Wood' },
  { vendor_id: 3108, fuel_type: 'Wood' },
  { vendor_id: 3109, fuel_type: 'Wood' },
  { vendor_id: 3110, fuel_type: 'Wood' },
  { vendor_id: 3111, fuel_type: 'Wood' },
  { vendor_id: 3112, fuel_type: 'Wood' },
  { vendor_id: 3113, fuel_type: 'Wood' },
  { vendor_id: 3114, fuel_type: 'Wood' },
  { vendor_id: 3115, fuel_type: 'Wood' },
  { vendor_id: 3116, fuel_type: 'Wood' },
  { vendor_id: 3117, fuel_type: 'Wood' },
  { vendor_id: 3118, fuel_type: 'Wood' },
  { vendor_id: 3119, fuel_type: 'Wood' },
  { vendor_id: 3120, fuel_type: 'Wood' },
  { vendor_id: 3121, fuel_type: 'Biofuel' },
  { vendor_id: 3122, fuel_type: 'Wood' },
  { vendor_id: 3123, fuel_type: 'Wood' },
  { vendor_id: 3124, fuel_type: 'Wood' },
  { vendor_id: 3124, fuel_type: 'Biofuel' },
  { vendor_id: 3125, fuel_type: 'Wood' },
  { vendor_id: 3126, fuel_type: 'Wood' },
  { vendor_id: 3127, fuel_type: 'Wood' },
  { vendor_id: 3128, fuel_type: 'Wood' },
  { vendor_id: 3129, fuel_type: 'Wood' },
  { vendor_id: 3130, fuel_type: 'Wood' },
  { vendor_id: 3132, fuel_type: 'Wood' },
  { vendor_id: 3133, fuel_type: 'Wood' },
  { vendor_id: 3134, fuel_type: 'Wood' },
  { vendor_id: 3135, fuel_type: 'Wood' },
  { vendor_id: 3136, fuel_type: 'Wood' },
  { vendor_id: 3137, fuel_type: 'Wood' },
  { vendor_id: 3138, fuel_type: 'Wood' },
  { vendor_id: 3139, fuel_type: 'Wood' },
  { vendor_id: 3140, fuel_type: 'Wood' },
  { vendor_id: 3141, fuel_type: 'Wood' },
  { vendor_id: 3142, fuel_type: 'Wood' },
  { vendor_id: 3143, fuel_type: 'Wood' },
  { vendor_id: 3144, fuel_type: 'Wood' },
  { vendor_id: 3145, fuel_type: 'Wood' },
  { vendor_id: 3146, fuel_type: 'Wood' },
  { vendor_id: 3147, fuel_type: 'Wood' },
  { vendor_id: 3148, fuel_type: 'Wood' },
  { vendor_id: 3149, fuel_type: 'Wood' },
  { vendor_id: 3150, fuel_type: 'Wood' },
  { vendor_id: 3151, fuel_type: 'Wood' },
  { vendor_id: 3152, fuel_type: 'Wood' },
  { vendor_id: 3153, fuel_type: 'Wood' },
  { vendor_id: 3154, fuel_type: 'Wood' },
  { vendor_id: 3155, fuel_type: 'Wood' },
  { vendor_id: 3156, fuel_type: 'Wood' },
  { vendor_id: 3157, fuel_type: 'Wood' },
  { vendor_id: 3158, fuel_type: 'Wood' },
  { vendor_id: 3159, fuel_type: 'Wood' },
  { vendor_id: 3160, fuel_type: 'Wood' },
  { vendor_id: 3161, fuel_type: 'Wood' },
  { vendor_id: 3162, fuel_type: 'Wood' },
  { vendor_id: 3163, fuel_type: 'Wood' },
  { vendor_id: 3164, fuel_type: 'Wood' },
  { vendor_id: 3165, fuel_type: 'Wood' },
  { vendor_id: 3166, fuel_type: 'Wood' },
  { vendor_id: 3167, fuel_type: 'Wood' },
  { vendor_id: 3168, fuel_type: 'Wood' },
  { vendor_id: 3169, fuel_type: 'Propane / LP' },
  { vendor_id: 3170, fuel_type: 'Wood' },
  { vendor_id: 3171, fuel_type: 'Wood' },
  { vendor_id: 3172, fuel_type: 'Wood' },
  { vendor_id: 3173, fuel_type: 'Wood' },
  { vendor_id: 3174, fuel_type: 'Wood' },
  { vendor_id: 3175, fuel_type: 'Wood' },
  { vendor_id: 3176, fuel_type: 'Wood' },
  { vendor_id: 3177, fuel_type: 'Wood' },
  { vendor_id: 3178, fuel_type: 'Wood' },
  { vendor_id: 3179, fuel_type: 'Wood' },
  { vendor_id: 3180, fuel_type: 'Wood' },
  { vendor_id: 3181, fuel_type: 'Wood' },
  { vendor_id: 3182, fuel_type: 'Wood' },
  { vendor_id: 3183, fuel_type: 'Propane / LP' },
  { vendor_id: 3184, fuel_type: 'Wood' },
  { vendor_id: 3185, fuel_type: 'Wood' },
  { vendor_id: 3186, fuel_type: 'Wood' },
  { vendor_id: 3187, fuel_type: 'Wood' },
  { vendor_id: 3188, fuel_type: 'Wood' },
  { vendor_id: 3189, fuel_type: 'Wood' },
  { vendor_id: 3190, fuel_type: 'Wood' },
  { vendor_id: 3191, fuel_type: 'Wood' },
  { vendor_id: 3192, fuel_type: 'Wood' },
  { vendor_id: 3193, fuel_type: 'Propane / LP' },
  { vendor_id: 3194, fuel_type: 'Wood' },
  { vendor_id: 3195, fuel_type: 'Wood' },
  { vendor_id: 3196, fuel_type: 'Wood' },
  { vendor_id: 3197, fuel_type: 'Wood' },
  { vendor_id: 3198, fuel_type: 'Wood' },
  { vendor_id: 3199, fuel_type: 'Wood' },
  { vendor_id: 3200, fuel_type: 'Wood' },
  { vendor_id: 3201, fuel_type: 'Wood' },
  { vendor_id: 3202, fuel_type: 'Propane / LP' },
  { vendor_id: 3203, fuel_type: 'Wood' },
  { vendor_id: 3204, fuel_type: 'Wood' },
  { vendor_id: 3205, fuel_type: 'Wood' },
  { vendor_id: 3206, fuel_type: 'Wood' },
  { vendor_id: 3207, fuel_type: 'Wood' },
  { vendor_id: 3208, fuel_type: 'Wood' },
  { vendor_id: 3209, fuel_type: 'Wood' },
  { vendor_id: 3210, fuel_type: 'Wood' },
  { vendor_id: 3211, fuel_type: 'Wood' },
  { vendor_id: 3212, fuel_type: 'Wood' },
  { vendor_id: 3213, fuel_type: 'Wood' },
  { vendor_id: 3214, fuel_type: 'Wood' },
  { vendor_id: 3215, fuel_type: 'Wood' },
  { vendor_id: 3216, fuel_type: 'Wood' },
  { vendor_id: 3218, fuel_type: 'Wood' },
  { vendor_id: 3219, fuel_type: 'Wood' },
  { vendor_id: 3220, fuel_type: 'Wood' },
  { vendor_id: 3221, fuel_type: 'Wood' },
  { vendor_id: 3222, fuel_type: 'Wood' },
  { vendor_id: 3223, fuel_type: 'Wood' },
  { vendor_id: 3224, fuel_type: 'Wood' },
  { vendor_id: 3225, fuel_type: 'Wood' },
  { vendor_id: 3226, fuel_type: 'Wood' },
  { vendor_id: 3227, fuel_type: 'Wood' },
  { vendor_id: 3228, fuel_type: 'Wood' },
  { vendor_id: 3229, fuel_type: 'Wood' },
  { vendor_id: 3230, fuel_type: 'Wood' },
  { vendor_id: 3231, fuel_type: 'Wood' },
  { vendor_id: 3232, fuel_type: 'Wood' },
  { vendor_id: 3233, fuel_type: 'Wood' },
  { vendor_id: 3234, fuel_type: 'Wood' },
  { vendor_id: 3235, fuel_type: 'Wood' },
  { vendor_id: 3236, fuel_type: 'Wood' },
  { vendor_id: 3237, fuel_type: 'Wood' },
  { vendor_id: 3238, fuel_type: 'Wood' },
  { vendor_id: 3239, fuel_type: 'Wood' },
  { vendor_id: 3240, fuel_type: 'Wood' },
  { vendor_id: 3241, fuel_type: 'Propane / LP' },
  { vendor_id: 3242, fuel_type: 'Wood' },
  { vendor_id: 3243, fuel_type: 'Wood' },
  { vendor_id: 3244, fuel_type: 'Electricity' },
  { vendor_id: 3245, fuel_type: 'Wood' },
  { vendor_id: 3246, fuel_type: 'Wood' },
  { vendor_id: 3247, fuel_type: 'Wood' },
  { vendor_id: 3248, fuel_type: 'Wood' },
  { vendor_id: 3249, fuel_type: 'Biofuel' },
  { vendor_id: 3250, fuel_type: 'Wood' },
  { vendor_id: 3251, fuel_type: 'Wood' },
  { vendor_id: 3252, fuel_type: 'Electricity' },
  { vendor_id: 3253, fuel_type: 'Wood' },
  { vendor_id: 3254, fuel_type: 'Wood' },
  { vendor_id: 3255, fuel_type: 'Wood' },
  { vendor_id: 3256, fuel_type: 'Wood' },
  { vendor_id: 3258, fuel_type: 'Wood' },
  { vendor_id: 3259, fuel_type: 'Wood' },
  { vendor_id: 3260, fuel_type: 'Wood' },
  { vendor_id: 3261, fuel_type: 'Wood' },
  { vendor_id: 3262, fuel_type: 'Wood' },
  { vendor_id: 3263, fuel_type: 'Wood' },
  { vendor_id: 3264, fuel_type: 'Wood' },
  { vendor_id: 3265, fuel_type: 'Biofuel' },
  { vendor_id: 3266, fuel_type: 'Wood' },
  { vendor_id: 3267, fuel_type: 'Electricity' },
  { vendor_id: 3268, fuel_type: 'Wood' },
  { vendor_id: 3269, fuel_type: 'Propane / LP' },
  { vendor_id: 3271, fuel_type: 'Electricity' },
  { vendor_id: 3272, fuel_type: 'Wood' },
  { vendor_id: 3273, fuel_type: 'Wood' },
  { vendor_id: 3274, fuel_type: 'Wood' },
  { vendor_id: 3275, fuel_type: 'Wood' },
  { vendor_id: 3276, fuel_type: 'Wood' },
  { vendor_id: 3277, fuel_type: 'Wood' },
  { vendor_id: 3278, fuel_type: 'Wood' },
  { vendor_id: 3279, fuel_type: 'Wood' },
  { vendor_id: 3280, fuel_type: 'Wood' },
  { vendor_id: 3281, fuel_type: 'Wood' },
  { vendor_id: 3282, fuel_type: 'Wood' },
  { vendor_id: 3283, fuel_type: 'Wood' },
  { vendor_id: 3284, fuel_type: 'Propane / LP' },
  { vendor_id: 3285, fuel_type: 'Propane / LP' },
  { vendor_id: 3286, fuel_type: 'Wood' },
  { vendor_id: 3287, fuel_type: 'Wood' },
  { vendor_id: 3288, fuel_type: 'Wood' },
  { vendor_id: 3289, fuel_type: 'Wood' },
  { vendor_id: 3290, fuel_type: 'Wood' },
  { vendor_id: 3291, fuel_type: 'Wood' },
  { vendor_id: 3292, fuel_type: 'Wood' },
  { vendor_id: 3293, fuel_type: 'Wood' },
  { vendor_id: 3294, fuel_type: 'Wood' },
  { vendor_id: 3295, fuel_type: 'Wood' },
  { vendor_id: 3297, fuel_type: 'Wood' },
  { vendor_id: 3298, fuel_type: 'Wood' },
  { vendor_id: 3299, fuel_type: 'Oil' },
  { vendor_id: 3300, fuel_type: 'Wood' },
  { vendor_id: 3301, fuel_type: 'Wood' },
  { vendor_id: 3302, fuel_type: 'Wood' },
  { vendor_id: 3303, fuel_type: 'Wood' },
  { vendor_id: 3304, fuel_type: 'Wood' },
  { vendor_id: 3305, fuel_type: 'Propane / LP' },
  { vendor_id: 3306, fuel_type: 'Wood' },
  { vendor_id: 3308, fuel_type: 'Wood' },
  { vendor_id: 3309, fuel_type: 'Wood' },
  { vendor_id: 3310, fuel_type: 'Wood' },
  { vendor_id: 3311, fuel_type: 'Wood' },
  { vendor_id: 3312, fuel_type: 'Propane / LP' },
  { vendor_id: 3313, fuel_type: 'Wood' },
  { vendor_id: 3314, fuel_type: 'Wood' },
  { vendor_id: 3315, fuel_type: 'Wood' },
  { vendor_id: 3316, fuel_type: 'Wood' },
  { vendor_id: 3317, fuel_type: 'Wood' },
  { vendor_id: 3318, fuel_type: 'Wood' },
  { vendor_id: 3319, fuel_type: 'Wood' },
  { vendor_id: 3320, fuel_type: 'Wood' },
  { vendor_id: 3321, fuel_type: 'Wood' },
  { vendor_id: 3322, fuel_type: 'Wood' },
  { vendor_id: 3323, fuel_type: 'Natural Gas' },
  { vendor_id: 3324, fuel_type: 'Wood' },
  { vendor_id: 3325, fuel_type: 'Wood' },
  { vendor_id: 3326, fuel_type: 'Wood' },
  { vendor_id: 3327, fuel_type: 'Biofuel' },
  { vendor_id: 3328, fuel_type: 'Wood' },
  { vendor_id: 3329, fuel_type: 'Wood' },
  { vendor_id: 3330, fuel_type: 'Wood' },
  { vendor_id: 3331, fuel_type: 'Wood' },
  { vendor_id: 3332, fuel_type: 'Natural Gas' },
  { vendor_id: 3333, fuel_type: 'Wood' },
  { vendor_id: 3334, fuel_type: 'Wood' },
  { vendor_id: 3335, fuel_type: 'Wood' },
  { vendor_id: 3336, fuel_type: 'Wood' },
  { vendor_id: 3337, fuel_type: 'Wood' },
  { vendor_id: 3338, fuel_type: 'Wood' },
  { vendor_id: 3339, fuel_type: 'Wood' },
  { vendor_id: 3340, fuel_type: 'Wood' },
  { vendor_id: 3341, fuel_type: 'Wood' },
  { vendor_id: 3342, fuel_type: 'Wood' },
  { vendor_id: 3343, fuel_type: 'Wood' },
  { vendor_id: 3344, fuel_type: 'Wood' },
  { vendor_id: 3345, fuel_type: 'Wood' },
  { vendor_id: 3346, fuel_type: 'Wood' },
  { vendor_id: 3347, fuel_type: 'Wood' },
  { vendor_id: 3348, fuel_type: 'Wood' },
  { vendor_id: 3349, fuel_type: 'Wood' },
  { vendor_id: 3350, fuel_type: 'Wood' },
  { vendor_id: 3351, fuel_type: 'Wood' },
  { vendor_id: 3352, fuel_type: 'Natural Gas' },
  { vendor_id: 3353, fuel_type: 'Wood' },
  { vendor_id: 3354, fuel_type: 'Wood' },
  { vendor_id: 3355, fuel_type: 'Natural Gas' },
  { vendor_id: 3355, fuel_type: 'Electricity' },
  { vendor_id: 3356, fuel_type: 'Wood' },
  { vendor_id: 3357, fuel_type: 'Wood' },
  { vendor_id: 3358, fuel_type: 'Wood' },
  { vendor_id: 3359, fuel_type: 'Wood' },
  { vendor_id: 3360, fuel_type: 'Wood' },
  { vendor_id: 3361, fuel_type: 'Wood' },
  { vendor_id: 3362, fuel_type: 'Wood' },
  { vendor_id: 3363, fuel_type: 'Wood' },
  { vendor_id: 3364, fuel_type: 'Propane / LP' },
  { vendor_id: 3365, fuel_type: 'Wood' },
  { vendor_id: 3366, fuel_type: 'Wood' },
  { vendor_id: 3367, fuel_type: 'Natural Gas' },
  { vendor_id: 3367, fuel_type: 'Electricity' },
  { vendor_id: 3368, fuel_type: 'Wood' },
  { vendor_id: 3369, fuel_type: 'Wood' },
  { vendor_id: 3370, fuel_type: 'Wood' },
  { vendor_id: 3371, fuel_type: 'Wood' },
  { vendor_id: 3372, fuel_type: 'Wood' },
  { vendor_id: 3373, fuel_type: 'Wood' },
  { vendor_id: 3374, fuel_type: 'Wood' },
  { vendor_id: 3375, fuel_type: 'Wood' },
  { vendor_id: 3376, fuel_type: 'Wood' },
  { vendor_id: 3377, fuel_type: 'Wood' },
  { vendor_id: 3378, fuel_type: 'Oil' },
  { vendor_id: 3379, fuel_type: 'Wood' },
  { vendor_id: 3380, fuel_type: 'Wood' },
  { vendor_id: 3381, fuel_type: 'Propane / LP' },
  { vendor_id: 3382, fuel_type: 'Wood' },
  { vendor_id: 3383, fuel_type: 'Wood' },
  { vendor_id: 3384, fuel_type: 'Wood' },
  { vendor_id: 3385, fuel_type: 'Wood' },
  { vendor_id: 3386, fuel_type: 'Wood' },
  { vendor_id: 3387, fuel_type: 'Wood' },
  { vendor_id: 3388, fuel_type: 'Wood' },
  { vendor_id: 3389, fuel_type: 'Wood' },
  { vendor_id: 3390, fuel_type: 'Wood' },
  { vendor_id: 3391, fuel_type: 'Wood' },
  { vendor_id: 3392, fuel_type: 'Wood' },
  { vendor_id: 3393, fuel_type: 'Wood' },
  { vendor_id: 3394, fuel_type: 'Wood' },
  { vendor_id: 3395, fuel_type: 'Wood' },
  { vendor_id: 3396, fuel_type: 'Wood' },
  { vendor_id: 3397, fuel_type: 'Wood' },
  { vendor_id: 3398, fuel_type: 'Wood' },
  { vendor_id: 3399, fuel_type: 'Wood' },
  { vendor_id: 3400, fuel_type: 'Wood' },
  { vendor_id: 3401, fuel_type: 'Wood' },
  { vendor_id: 3402, fuel_type: 'Wood' },
  { vendor_id: 3403, fuel_type: 'Wood' },
  { vendor_id: 3404, fuel_type: 'Wood' },
  { vendor_id: 3405, fuel_type: 'Wood' },
  { vendor_id: 3406, fuel_type: 'Wood' },
  { vendor_id: 3407, fuel_type: 'Wood' },
  { vendor_id: 3408, fuel_type: 'Wood' },
  { vendor_id: 3409, fuel_type: 'Wood' },
  { vendor_id: 3411, fuel_type: 'Wood' },
  { vendor_id: 3412, fuel_type: 'Wood' },
  { vendor_id: 3413, fuel_type: 'Wood' },
  { vendor_id: 3414, fuel_type: 'Propane / LP' },
  { vendor_id: 3415, fuel_type: 'Propane / LP' },
  { vendor_id: 3416, fuel_type: 'Propane / LP' },
  { vendor_id: 3417, fuel_type: 'Wood' },
  { vendor_id: 3418, fuel_type: 'Propane / LP' },
  { vendor_id: 3418, fuel_type: 'Oil' },
  { vendor_id: 3419, fuel_type: 'Wood' },
  { vendor_id: 3420, fuel_type: 'Wood' },
  { vendor_id: 3421, fuel_type: 'Wood' },
  { vendor_id: 3422, fuel_type: 'Wood' },
  { vendor_id: 3423, fuel_type: 'Wood' },
  { vendor_id: 3424, fuel_type: 'Wood' },
  { vendor_id: 3425, fuel_type: 'Natural Gas' },
  { vendor_id: 3426, fuel_type: 'Wood' },
  { vendor_id: 3427, fuel_type: 'Wood' },
  { vendor_id: 3428, fuel_type: 'Wood' },
  { vendor_id: 3429, fuel_type: 'Wood' },
  { vendor_id: 3430, fuel_type: 'Wood' },
  { vendor_id: 3431, fuel_type: 'Wood' },
  { vendor_id: 3432, fuel_type: 'Wood' },
  { vendor_id: 3433, fuel_type: 'Wood' },
  { vendor_id: 3434, fuel_type: 'Wood' },
  { vendor_id: 3435, fuel_type: 'Wood' },
  { vendor_id: 3436, fuel_type: 'Wood' },
  { vendor_id: 3437, fuel_type: 'Wood' },
  { vendor_id: 3438, fuel_type: 'Wood' },
  { vendor_id: 3439, fuel_type: 'Wood' },
  { vendor_id: 3440, fuel_type: 'Wood' },
  { vendor_id: 3441, fuel_type: 'Wood' },
  { vendor_id: 3442, fuel_type: 'Wood' },
  { vendor_id: 3443, fuel_type: 'Wood' },
  { vendor_id: 3444, fuel_type: 'Wood' },
  { vendor_id: 3445, fuel_type: 'Wood' },
  { vendor_id: 3446, fuel_type: 'Wood' },
  { vendor_id: 3447, fuel_type: 'Wood' },
  { vendor_id: 3448, fuel_type: 'Wood' },
  { vendor_id: 3449, fuel_type: 'Electricity' },
  { vendor_id: 3449, fuel_type: 'Propane / LP' },
  { vendor_id: 3450, fuel_type: 'Propane / LP' },
  { vendor_id: 3451, fuel_type: 'Wood' },
  { vendor_id: 3452, fuel_type: 'Wood' },
  { vendor_id: 3453, fuel_type: 'Biofuel' },
  { vendor_id: 3454, fuel_type: 'Wood' },
  { vendor_id: 3455, fuel_type: 'Wood' },
  { vendor_id: 3456, fuel_type: 'Wood' },
  { vendor_id: 3457, fuel_type: 'Natural Gas' },
  { vendor_id: 3458, fuel_type: 'Wood' },
  { vendor_id: 3459, fuel_type: 'Natural Gas' },
  { vendor_id: 3460, fuel_type: 'Wood' },
  { vendor_id: 3461, fuel_type: 'Wood' },
  { vendor_id: 3462, fuel_type: 'Wood' },
  { vendor_id: 3463, fuel_type: 'Electricity' },
  { vendor_id: 3464, fuel_type: 'Electricity' },
  { vendor_id: 3464, fuel_type: 'Propane / LP' },
  { vendor_id: 3465, fuel_type: 'Wood' },
  { vendor_id: 3466, fuel_type: 'Wood' },
  { vendor_id: 3467, fuel_type: 'Wood' },
  { vendor_id: 3468, fuel_type: 'Wood' },
  { vendor_id: 3469, fuel_type: 'Wood' },
  { vendor_id: 3470, fuel_type: 'Wood' },
  { vendor_id: 3471, fuel_type: 'Wood' },
  { vendor_id: 3472, fuel_type: 'Wood' },
  { vendor_id: 3473, fuel_type: 'Wood' },
  { vendor_id: 3474, fuel_type: 'Propane / LP' },
  { vendor_id: 3475, fuel_type: 'Wood' },
  { vendor_id: 3476, fuel_type: 'Wood' },
  { vendor_id: 3477, fuel_type: 'Wood' },
  { vendor_id: 3479, fuel_type: 'Propane / LP' },
  { vendor_id: 3480, fuel_type: 'Wood' },
  { vendor_id: 3481, fuel_type: 'Wood' },
  { vendor_id: 3482, fuel_type: 'Wood' },
  { vendor_id: 3483, fuel_type: 'Wood' },
  { vendor_id: 3484, fuel_type: 'Wood' },
  { vendor_id: 3485, fuel_type: 'Wood' },
  { vendor_id: 3486, fuel_type: 'Wood' },
  { vendor_id: 3487, fuel_type: 'Wood' },
  { vendor_id: 3488, fuel_type: 'Wood' },
  { vendor_id: 3489, fuel_type: 'Wood' },
  { vendor_id: 3490, fuel_type: 'Wood' },
  { vendor_id: 3491, fuel_type: 'Wood' },
  { vendor_id: 3492, fuel_type: 'Wood' },
  { vendor_id: 3493, fuel_type: 'Wood' },
  { vendor_id: 3494, fuel_type: 'Propane / LP' },
  { vendor_id: 3494, fuel_type: 'Oil' },
  { vendor_id: 3495, fuel_type: 'Wood' },
  { vendor_id: 3496, fuel_type: 'Wood' },
  { vendor_id: 3497, fuel_type: 'Propane / LP' },
  { vendor_id: 3497, fuel_type: 'Oil' },
  { vendor_id: 3498, fuel_type: 'Propane / LP' },
  { vendor_id: 3499, fuel_type: 'Wood' },
  { vendor_id: 3500, fuel_type: 'Electricity' },
  { vendor_id: 3501, fuel_type: 'Propane / LP' },
  { vendor_id: 3503, fuel_type: 'Wood' },
  { vendor_id: 3504, fuel_type: 'Natural Gas' },
  { vendor_id: 3505, fuel_type: 'Wood' },
  { vendor_id: 3506, fuel_type: 'Wood' },
  { vendor_id: 3507, fuel_type: 'Wood' },
  { vendor_id: 3508, fuel_type: 'Wood' },
  { vendor_id: 3509, fuel_type: 'Wood' },
  { vendor_id: 3510, fuel_type: 'Wood' },
  { vendor_id: 3511, fuel_type: 'Wood' },
  { vendor_id: 3512, fuel_type: 'Propane / LP' },
  { vendor_id: 3513, fuel_type: 'Wood' },
  { vendor_id: 3514, fuel_type: 'Propane / LP' },
  { vendor_id: 3515, fuel_type: 'Wood' },
  { vendor_id: 3516, fuel_type: 'Wood' },
  { vendor_id: 3517, fuel_type: 'Wood' },
  { vendor_id: 3518, fuel_type: 'Wood' },
  { vendor_id: 3519, fuel_type: 'Wood' },
  { vendor_id: 3520, fuel_type: 'Wood' },
  { vendor_id: 3521, fuel_type: 'Wood' },
  { vendor_id: 3522, fuel_type: 'Wood' },
  { vendor_id: 3523, fuel_type: 'Wood' },
  { vendor_id: 3524, fuel_type: 'Wood' },
  { vendor_id: 3525, fuel_type: 'Wood' },
  { vendor_id: 3526, fuel_type: 'Wood' },
  { vendor_id: 3527, fuel_type: 'Wood' },
  { vendor_id: 3528, fuel_type: 'Wood' },
  { vendor_id: 3529, fuel_type: 'Wood' },
  { vendor_id: 3530, fuel_type: 'Wood' },
  { vendor_id: 3531, fuel_type: 'Oil' },
  { vendor_id: 3531, fuel_type: 'Propane / LP' },
  { vendor_id: 3532, fuel_type: 'Wood' },
  { vendor_id: 3533, fuel_type: 'Wood' },
  { vendor_id: 3534, fuel_type: 'Electricity' },
  { vendor_id: 3535, fuel_type: 'Wood' },
  { vendor_id: 3536, fuel_type: 'Wood' },
  { vendor_id: 3537, fuel_type: 'Wood' },
  { vendor_id: 3538, fuel_type: 'Electricity' },
  { vendor_id: 3539, fuel_type: 'Wood' },
  { vendor_id: 3540, fuel_type: 'Electricity' },
  { vendor_id: 3541, fuel_type: 'Wood' },
  { vendor_id: 3542, fuel_type: 'Biofuel' },
  { vendor_id: 3543, fuel_type: 'Natural Gas' },
  { vendor_id: 3544, fuel_type: 'Propane / LP' },
  { vendor_id: 3545, fuel_type: 'Oil' },
  { vendor_id: 3545, fuel_type: 'Propane / LP' },
  { vendor_id: 3546, fuel_type: 'Wood' },
  { vendor_id: 3547, fuel_type: 'Wood' },
  { vendor_id: 3548, fuel_type: 'Wood' },
  { vendor_id: 3549, fuel_type: 'Wood' },
  { vendor_id: 3550, fuel_type: 'Wood' },
  { vendor_id: 3551, fuel_type: 'Wood' },
  { vendor_id: 3552, fuel_type: 'Wood' },
  { vendor_id: 3553, fuel_type: 'Wood' },
  { vendor_id: 3554, fuel_type: 'Wood' },
  { vendor_id: 3555, fuel_type: 'Wood' },
  { vendor_id: 3556, fuel_type: 'Natural Gas' },
  { vendor_id: 3556, fuel_type: 'Electricity' },
  { vendor_id: 3557, fuel_type: 'Wood' },
  { vendor_id: 3558, fuel_type: 'Wood' },
  { vendor_id: 3559, fuel_type: 'Wood' },
  { vendor_id: 3560, fuel_type: 'Wood' },
  { vendor_id: 3560, fuel_type: 'Biofuel' },
  { vendor_id: 3561, fuel_type: 'Electricity' },
  { vendor_id: 3561, fuel_type: 'Propane / LP' },
  { vendor_id: 3562, fuel_type: 'Wood' },
  { vendor_id: 3564, fuel_type: 'Wood' },
  { vendor_id: 3565, fuel_type: 'Wood' },
  { vendor_id: 3566, fuel_type: 'Wood' },
  { vendor_id: 3567, fuel_type: 'Wood' },
  { vendor_id: 3568, fuel_type: 'Wood' },
  { vendor_id: 3569, fuel_type: 'Wood' },
  { vendor_id: 3570, fuel_type: 'Natural Gas' },
  { vendor_id: 3570, fuel_type: 'Electricity' },
  { vendor_id: 3571, fuel_type: 'Wood' },
  { vendor_id: 3572, fuel_type: 'Propane / LP' },
  { vendor_id: 3573, fuel_type: 'Wood' },
  { vendor_id: 3574, fuel_type: 'Wood' },
  { vendor_id: 3575, fuel_type: 'Wood' },
  { vendor_id: 3577, fuel_type: 'Wood' },
  { vendor_id: 3578, fuel_type: 'Wood' },
  { vendor_id: 3579, fuel_type: 'Oil' },
  { vendor_id: 3580, fuel_type: 'Wood' },
  { vendor_id: 3581, fuel_type: 'Wood' },
  { vendor_id: 3582, fuel_type: 'Natural Gas' },
  { vendor_id: 3582, fuel_type: 'Electricity' },
  { vendor_id: 3583, fuel_type: 'Electricity' },
  { vendor_id: 3583, fuel_type: 'Natural Gas' },
  { vendor_id: 3584, fuel_type: 'Wood' },
  { vendor_id: 3585, fuel_type: 'Natural Gas' },
  { vendor_id: 3585, fuel_type: 'Electricity' },
  { vendor_id: 3586, fuel_type: 'Wood' },
  { vendor_id: 3587, fuel_type: 'Wood' },
  { vendor_id: 3588, fuel_type: 'Oil' },
  { vendor_id: 3589, fuel_type: 'Wood' },
  { vendor_id: 3590, fuel_type: 'Natural Gas' },
  { vendor_id: 3590, fuel_type: 'Electricity' },
  { vendor_id: 3591, fuel_type: 'Wood' },
  { vendor_id: 3592, fuel_type: 'Propane / LP' },
  { vendor_id: 3592, fuel_type: 'Oil' },
  { vendor_id: 3593, fuel_type: 'Wood' },
  { vendor_id: 3594, fuel_type: 'Wood' },
  { vendor_id: 3595, fuel_type: 'Wood' },
  { vendor_id: 3596, fuel_type: 'Wood' },
  { vendor_id: 3597, fuel_type: 'Propane / LP' },
  { vendor_id: 3598, fuel_type: 'Electricity' },
  { vendor_id: 3600, fuel_type: 'Wood' },
  { vendor_id: 3601, fuel_type: 'Wood' },
  { vendor_id: 3602, fuel_type: 'Biofuel' },
  { vendor_id: 3603, fuel_type: 'Wood' },
  { vendor_id: 3604, fuel_type: 'Wood' },
  { vendor_id: 3605, fuel_type: 'Wood' },
  { vendor_id: 3606, fuel_type: 'Electricity' },
  { vendor_id: 4762, fuel_type: 'Natural Gas' },
  { vendor_id: 4767, fuel_type: 'Wood' },
  { vendor_id: 4788, fuel_type: 'Wood' },
  { vendor_id: 4789, fuel_type: 'Wood' },
  { vendor_id: 4790, fuel_type: 'Wood' },
  { vendor_id: 4791, fuel_type: 'Wood' },
  { vendor_id: 4791, fuel_type: 'Biofuel' },
  { vendor_id: 14793, fuel_type: 'Wood' }
]
// initial state
const state = () => ({
  All: _VendorFuels
})

// getters
const getters = {
}

// actions
const actions = {
}

// mutations
const mutations = {
}

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
